### ISSUE TITLE
feat: Add CI/CD pipeline to create builds for each commit and release

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#100]
**What feature would you like added?**
We probably wanna add some CI/CD pipeline (probably just GitHub actions) to create builds of each commit pushed to the repo as well as creating builds on release.

**Why should this feature be added?**
CI/CD pipeline would improve testing new features by 3rd parties. E.g. some user requests feature, new branch gets created and feature implemented, CI/CD builds package in all formats, user can download package and test it themselves without needing to build from source.

Additional we could also add integration testing to spot bugs early but my main idea was to use it to build packages for each commit to test new features without needing to setup a build environment.

**Additional Info**
For some reason GitHub actions are super lenient when it comes to free CI time. Northstar org for example has unlimited CI build time (including Windows hosts, which honestly is ridiculous ^^) so using up free CI time per month shouldn't be a worry.

**Comment by 0neGal** [comment]
To be quite frank, I've never actually used GitHub Actions, and have no clue how to set it up, but I'm open to implementing/setting it up... I'll try to look into how to set it up, at some point, if need be.
