### ISSUE TITLE
bug: Improper handling of no internet

### ISSUE THREAD

**Issue by 0neGal** [0neGal/viper#105]
**Describe the bug**
When launching Viper without an internet connection you may see various errors, related to your DNS not being set, and so on. This isn't very useful to a user.

**To Reproduce**
1. Disconnect your internet
2. Launch Viper
3. Errors occur

**Expected behavior**
A more descriptive alert box, or simply Viper launching as normal but without functionalities that require an internet connection. If we go for the latter `requests.js` should probably just return a cached version of the release notes and so on, even if it's supposed to have been refreshed. As to not have empty release notes, however we should still expect that a new user may not have an internet connection and so we should still display an error if no cache is found.

**Screenshots**
There's 3 identical error alerts, stemming from our 3 `api.github.com` requests (NS latest version, NS release notes and Viper release notes) in `requests.js`

<p align="center">
    <img src="https://user-images.githubusercontent.com/33325154/160244936-6334b4df-ae3a-4fb4-b429-e03e66a9d2f2.png">
</p>

**Comment by Alystrasz** [comment]
I'll take a look at this.
