### ISSUE TITLE
bug: Release notes of Northstar `v1.6.0` not properly rendered in Viper

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#108]
**Describe the bug**
The release notes of Northstar `v1.6.0` are not properly rendered in Viper

**To Reproduce**
1. Go to Northstar -> _Release Notes_ within Viper
2. Scroll down to _v1.6.0_
3. Unlike other versions, the links to the mentioned PRs in the release notes are not properly formatted

**Expected behavior**
The linked PRs in the release notes should be properly rendered like with release notes for other versions of Northstar.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/40122905/162638666-1c8afee9-45f0-4413-a634-1ac77c94b71d.png)

**Version:**
`v1.3.1`

**Additional Info**

My assumption is that whatever library Viper uses for rendering Markdown, it does not properly handle HTML tags in the release note contents. For reference, here's the head of the Northstar `v1.6.0` release notes

```
<div>
    <a><img src="https://user-images.githubusercontent.com/16687318/156849195-06d5c58f-d472-45a7-9ec4-26abc72bc27f.png" width="49%"></a>
    <a><img src="https://user-images.githubusercontent.com/16687318/154815173-454084a4-3b88-48ca-b62b-6df09fe853ff.png" width="49%"></a>
</div>

**Features**
Update private match map select menu ([#194](https://github.com/R2Northstar/NorthstarLauncher/pull/194))
```

I'm well aware that this is more of a minor issue and has no priority to be fixed. However depending on how _"stylish"_ we go with future release notes for Northstar by using HTML tags for embedding images in a certain layout, it will again not get properly rendered within Viper ^^

**Comment by 0neGal** [comment]
Even tho this is low priority I still will try to have a look at it when I got the time, the easiest solution might just be switching out the package we use for converting the Markdown to HTML...

**Comment by 0neGal** [comment]
From what I can tell, what breaks it, is the fact that the release notes tries to use `<div>` tags, which aren't technically valid Markdown, albeit they usually just get put together with the HTML'ed Markdown when converting in a lot of instances, however I think as to make the notes not get all crazy, and do all kinds of workarounds, the best way to deal with this is simple to omit `<div>` tags alltogether.

**Comment by 0neGal** [comment]
The specific issue actually seems more with the way we parse the Markdown, because of the fact that newlines in Markdown require two newlines to count as a line break, we have to add one extra line in quite a few places, due to the way NS' releases are formatted.

This ended up causing an issue that placed no line between valid Markdown and the `<div>`, i.e:

```html
<div></div>
**Test**
```

Becomes that because there's no line between the `<div>` element and the Markdown, which causes the issue. I'll try and touch up the Markdown parsing code and see if I can get this solved...

**Comment by 0neGal** [comment]
Turns out, `marked`, the library we use, in all it's glory, has an option to parse linebreaks the same way GitHub parses them, fixing this!
