### ISSUE TITLE
bug: Viper puts itself in french and I don't know how to change it

### ISSUE THREAD

**Issue by Sigmania** [0neGal/viper#109]
**Describe the bug**

**To Reproduce**
1. Install Viper on a french pc
2. Close it, then open it again

**Expected behavior**
Supposed to be in english, ask what language I want to use or at least let me change it in-app

**Screenshots**
![image](https://user-images.githubusercontent.com/78875092/162842346-01ee2775-38d1-43fd-95a8-5014ad875d9b.png)

**Version:**
1.3.1

**Additional Info**
My pc is in french but I like having the apps in english

**Comment by Sigmania** [comment]
Alright I managed to change it by modifying the Properties file

**Comment by 0neGal** [comment]
I'll keep this open, as I'll likely look into a way to force it in app, the reason this happens is it fetches your system language on startup and writes it to the settings file every time. However it's mostly low-priority...

**Comment by Sigmania** [comment]
Yeah it doesn't even seem to be permanent. First time I tried it it worked, closed it, opened it, didn't work. Uninstalled, re-installed, edited Properties, opened it, didn't work! It's not that big a problem, I mean it's not for nothing my pc's in french, but it would still be appreciated if we could choose the language in the app.

**Comment by 0neGal** [comment]
Generally Viper prioritizes the language in the settings file (`viper.json`), however after reading the settings file if an invalid language is set, or simply isn't set (first launch), it'll try to read the system. If it succeeds it writes it to the settings file.

However if it finds a valid language it'll use it, then it'll once again save the settings file with the system language, in case the user changed it. Leading to that behaviour... I'll implement a setting (when I got time) to disable Viper trying to read the systems language, and then let the user choose.

**Comment by Sigmania** [comment]
Wow thanks! That's really appreciated!

**Comment by 0neGal** [comment]
The upstream branch now has this implemented, meaning it'll be out in the next release!
