### ISSUE TITLE
Distribution formats

### ISSUE THREAD

**Issue by 0neGal** [0neGal/viper#11]
As briefly discussed in a PR we need to consider which distribution format we're going to use (#2)

> > It doesn't seem like it is reproducible, and must just be Windows caching the icon or something similar, because I built and installed it, and the icon popped up just fine, everywhere.
> 
> 
> Perfect then!
> 
> > I'm more referring to whether or not there's any other install methods we should include, like .deb, .tar.gz, pacman package, .rpm. Personally I think all of those which I just mentioned should be included. I don't think a snap package is really in the interest, of literally anyone. And if we have the tar file there's no point in zip, or other archive formats. As for Windows, besides the installer, a portable build might also be convenient.
> 
> We should discuss it on a dedicated issue I think, because choosing distribution format implies a lot of things (about Windows for instance, if you want your app to be able to update itself with GitHub releases, it's only possible with NSIS format)

**Comment by Alystrasz** [comment]
As I mentioned previously, from a features point of view, the [auto update mechanism](https://www.electron.build/auto-update.html) is only usable in Linux AppImage, Windows NSIS and macOS DMGs.

- Do we need another Windows format? I think NSIS already provides a standalone executable
- Is Titanfall playable on mac? I really have no idea
- Since Viper can be used to update servers potentially running on Linux, is the AppImage format adequate?

**Comment by 0neGal** [comment]
> Do we need another Windows format? I think NSIS already provides a standalone executable

NSIS installs it into your local AppData Programs folder, with all it's files, a portable executable is one file and nothing else. It's simply for the sake of it, while I see most users sticking to the installers a portable won't do no harm and I think it has a purpose.

> Is Titanfall playable on mac? I really have no idea

Nope, not without Wine and since Wine isn't supported on newer version of macOS we don't have to worry about it.

> Since Viper can be used to update servers potentially running on Linux, is the AppImage format adequate?

Hence the various package manager formats, along with a tar file. If all those aren't enough I'm not sure any are.


As for auto-updating, I'll look at implementing...

**Comment by Alystrasz** [comment]
> NSIS installs it into your local AppData Programs folder, with all it's files, a portable executable is one file and nothing else. It's simply for the sake of it, while I see most users sticking to the installers a portable won't do no harm and I think it has a purpose.

Why not proposing a portable executable then, it's only a flag to add to the compile command.


> > Is Titanfall playable on mac? I really have no idea
> 
> Nope, not without Wine and since Wine isn't supported on newer version of macOS we don't have to worry about it.

Let's forget about Mac then :)


> > Since Viper can be used to update servers potentially running on Linux, is the AppImage format adequate?
> 
> Hence the various package manager formats, along with a tar file. If all those aren't enough I'm not sure any are.


I'm not very familiar with AppImage, but isn't the point of this format to run on all distros (removing the need to compile a .deb, a .rpm etc)?

**Comment by 0neGal** [comment]
> I'm not very familiar with AppImage, but isn't the point of this format to run on all distros (removing the need to compile a .deb, a .rpm etc)?

That is the purpose of AppImages, however I and many other people don't like using AppImages for everything, not having it in your package manager may not be what everybody wants. 

I just know for myself, only having AppImages as the option is not always what you want. But yes they would lose the function all to auto update, unless we add these packages directly in the repos for that distro.
