### ISSUE TITLE
JavaScript error on startup

### ISSUE THREAD

**Issue by JimmyGrinch** [0neGal/viper#110]
**Describe the bug**
Error window appears on startup
clicking ok gives a different error window with a similar message
Viper window still pops up but no buttons work
Game still runs on steam
worked fairly recently, don't think I made any major changes to computer settings

Is this a problem with my computer or a glitch in the program

version 1.3.1
already tried reinstalling viper, same problem
![delete](https://user-images.githubusercontent.com/74577141/162864242-dc306191-0325-4df1-bd85-fa2aeb4cb9f4.png)
![delete1](https://user-images.githubusercontent.com/74577141/162864533-f0738933-4286-464f-b264-790be6b99656.png)

**Comment by 0neGal** [comment]
Can you verify that the game path still exists? (`C:/Program Files (x86)/Steam/steamapps/common/Titanfall2`)

The error happens because it's trying to read and write in a folder that doesn't exist.

Perhaps you moved where the game was located or similar...

**Comment by JimmyGrinch** [comment]
oof im stupid. Yes that was the cause of it, I swapped drives and was able to fix the game path, but I did have to click through about 15 error boxes with viper/the path dialogue loading inbetween.
Thanks!

**Comment by 0neGal** [comment]
> but I did have to click through about 15 error boxes with viper/the path dialogue loading inbetween.

I'll have to implement some checks to stop that... :p

**Comment by 0neGal** [comment]
> Experienced this recently, my library is on an external drive and i forgot to plug it in before opening Viper

I'll add an error alert if the folder doesn't exist on startup, and disable updating and installing mods etc, until you restart.

**Comment by 0neGal** [comment]
This is now implemented and will be in the next release!
