### ISSUE TITLE
i18n: language settings and more

### ISSUE THREAD

**Issue by 0neGal** [0neGal/viper#111]
@Alystrasz, @AA-Delta some more strings that need translation :)

```json
"cli.gamepath.lost": "Gamepath not found, make sure it's mounted!",

"gui.settings.title.language": "Language",
"gui.settings.autolang.title": "Auto-Detect Language",
"gui.settings.autolang.desc": "When enabled, Viper tries to automatically detect your system language, when disabled you can manually change the language below.",
"gui.settings.forcedlang.title": "Language",
"gui.settings.forcedlang.desc": "When \"Auto-Detect Language\" is disabled, this will decide the language. Requires a restart to take effect.",

"gui.gamepath.lost": "Gamepath no longer exists/can't be found!\n\nMake sure your drive is mounted properly, or if you moved your game location that you update the game path.\n\nViper may not work properly until next restart!",
```

Also with the new language selectors I had to make more user friendly names for the languages, and chose to do add a `lang.title` in the top of the files, which is what it shows up as in the settings. I translated them with Google Translate, but given they're just the name of the language, in it's language I don't assume there's any real way Google can mess this one up. But please do check it just to make sure.

 - [x] French (`fr.json`)
 - [x] Spanish (`es.json`)

**Comment by AA-Delta** [comment]
#113
Sorry for the delay. 
> I don't assume there's any real way Google can mess this one up. But please do check it just to make sure.

Yep, it did mess up
