### ISSUE TITLE
bug: Switching Language has no effect in Viper AppImage

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#115]
**Describe the bug**
The option to manually set language seems to have no effect when using the Viper AppImage.

**To Reproduce**
1. Go to Settings
2. Set language to French (assuming current version is English)
3. Restart Viper
4. The settings now claim the language is French but Viper UI is still in English.

**Expected behavior**
Language change should be applied to UI after restart.

**Screenshots**
![image](https://user-images.githubusercontent.com/40122905/163693277-cfd994c9-07d2-4d6d-ab78-42f8c927758b.png)

**Version:**
`v1.3.2`

**Additional Info**
Viper Flatpak also crashes completely but that seems to related due to unpacking the AppImage and is discussed in https://github.com/flathub/com.github._0negal.Viper/issues/1

**Comment by 0neGal** [comment]
In the screenshot it looks like you haven't turned off **"Auto-Detect Language"**

Unless that screenshot was taken before disabling that?

**Comment by GeckoEidechse** [comment]
Ah, there's the issue then. I completely missed the "_Auto-Detect Language_" switch and just assumed changing it in the dropdown field below would act as an overwrite ^^"

Maybe selecting a language should also turn "_Auto-Detect Language_" off automatically? Or the menu to select a language should be locked until "_Auto-Detect Language_" is off?
Just something to prevent being able to change a setting that doesn't have an observable effect which usually ends up confusing the user (in that case me :P)

**Comment by 0neGal** [comment]
I'll add an `onchange` event to auto toggle it when the language is changed.

I'll keep the issue open as a reminder! :)

**Comment by 0neGal** [comment]
This should now be implemented! :)

**Comment by GeckoEidechse** [comment]
Works as intended on Viper 1.6.3 Flatpak release.
