### ISSUE TITLE
Viper throws JSON error on startup

### ISSUE THREAD

**Issue by 3nderall** [0neGal/viper#119]
I get a json error

Have titanfall not installed on a filepath other than default

It launches, then this error message appears:

![error message](https://user-images.githubusercontent.com/33325154/165562093-7601c606-c54a-4f73-a0d1-5b0a304758f6.png)

version: 1.3.4

**Comment by 0neGal** [comment]
It's the JSON parser essentially saying "your config file is formatted incorrectly", no clue how this would even happen, could you try and give me the content of your config file, it should be located at `%APPDATA%/viper.json`, you can simply run that path inside the <kbd>Win+R</kbd> window, then open the file with notepad. (`notepad.exe %APPDATA%/viper.json` might also work)

**Comment by 3nderall** [comment]
{"gamepath":"C:\\Program Files\ea games\Titanfall2//","lang":"en-GB","nsupdate":true,"autoupdate":true,"nsargs":"-multiple","zip":"C:\\Program Files\\EA Games\\Titanfall2\\northstar.zip","excludes":["ns_startup_args.txt","ns_startup_args_dedi.txt"]}

Text in the config file

**Comment by GeckoEidechse** [comment]
Ok, so the issue is the game path in the JSON file isn't properly formatted. It should be:
```json
"gamepath":"C:\\Program Files\\ea games\\Titanfall2\\"
```
instead of
```json
"gamepath":"C:\Program Files\ea games\Titanfall2//"
```

Same with:
```json
"zip":"C:\Program Files\EA Games\Titanfall2\northstar.zip"
```
which should be
```json
"zip":"C:\\Program Files\\EA Games\\Titanfall2\\northstar.zip"
```

&nbsp;

@3nderall did you manually edit that file by chance?

Anyway, probably the easiest way to fix it is to delete that `viper.json` file and then starting Viper again. It should recreate the file, though you might get asked to select the Titanfall2 install folder again (not sure if Viper does auto-detecting of EA App installed Titanfall yet).

**Comment by 0neGal** [comment]
Yeah that's what I figured as well, I don't see why this would ever happen as I'm fairly certain `JSON.stringify()` adds extra backslashes to escape them, and so the only way this could've happened is from the config being manually edited.

Even if that's the case I think a proper error message should pop up notifying the user that the config couldn't be loaded properly.

**Comment by GeckoEidechse** [comment]
> Even if that's the case I think a proper error message should pop up notifying the user that the config couldn't be loaded properly.

Sounds like a good idea. Maybe also with an option to "reset" it, i.e. just delete and recreate. ^^

**Comment by 3nderall** [comment]
> 
> @3nderall did you manually edit that file by chance?
> 


No I haven't. Is there anyway to change the game path to my own tf2 install directory?

**Comment by 0neGal** [comment]
If it doesn't auto detect your game path it'll ask you to select one manually, if it does detect one but it's still incorrect you can go onto the main Viper page (first button in the sidebar) and click **"Change Gamepath"**, that'll allow you to manually change it without messing with the config or anything.

**Comment by 0neGal** [comment]
This should now be fully functioning, and will therefore be in the next release, feel free to open the issue if removing the config didn't solve the problem or related.
