### ISSUE TITLE
feat: Master server status

### ISSUE THREAD

**Issue by 0neGal** [0neGal/viper#129]
**What feature would you like added?**
An indicator for whether the master server is currently up, along with server count and player count etc

**Why should this feature be added?**
It's useful, as some people get authentication errors and thinks it's only on their side, besides that it's obvious usefulness shouldn't need explanation.

**Additional Info**
Hopefully @GeckoEidechse knows exactly how this would be done, I know there's a JSON file somewhere for the server browser, I can't remember the link.

And even then I don't know what the best way to check if the master server is up.

**Comment by GeckoEidechse** [comment]
`/client/servers` is what you're looking for server browser list. Total playercount is just all individual server playercounts added up.

Though there have been cases where the server list was available but authentication still failed. Should be a close enough proxy though ^^

**Comment by 0neGal** [comment]
> `/client/servers` is what you're looking for server browser list. Total playercount is just all individual server playercounts added up.

ah, it's already in my search history

> Though there have been cases where the server list was available but authentication still failed. Should be a close enough proxy though ^^

It's more for cases like right now, where the master server is directly down, I'll have a look at implementing it once it's up again! Many thanks!
