### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#13]
Viper should also allow installing/removing Northstar mods.
We should also think how we can update them, since there's no standard version to do it (yet).

**Comment by 0neGal** [comment]
For reference this is how the UI looks currently.

![](https://user-images.githubusercontent.com/33325154/147831543-9d348f02-927a-429c-809e-850a8f0fe836.png)

As for updating them, NorthstarMods themselves, the default ones are already updated when updating Northstar itself, although I have slight improvements I wanna implement, as for updating other mods it'd just overwrite the mod if it's already installed, actually implementing mod management isn't all that hard...

As for toggling mods, I'm thinking we just put them in a `disabled` folder, I don't know how Juicy's works in terms of disabling mods... If we knew that we could have both mod managers be able to disable and enable mods.

One big issue with supporting mods, or not big, but for some oddball reason the default mods have an improperly formatted `mod.json` file I [already made a PR](https://github.com/R2Northstar/NorthstarMods/pull/38) for it. So currently the little code I have pushed to the `mod-support` branch won't work by default without my PR. Quite an issue.

**Comment by Alystrasz** [comment]
Sounds like `disabled` folder option sounds good while there's no standard way to do this.

**Comment by 0neGal** [comment]
Exactly, it'd be nice if there was a simpler way like just renaming the folder and appending a "." or "_" or something and then Northstar just didn't load it, but the folder is really future proof so it's probably the better option...

**Comment by 0neGal** [comment]
A big issue I'm running into is several mods simply do not format their `mod.json` file properly causing parser errors... Actually quite annoying, not only do other third party mods do this but also the base Northstar mods as mentioned before.

**Comment by Alystrasz** [comment]
> A big issue I'm running into is several mods simply do not format their `mod.json` file properly causing parser errors... Actually quite annoying, not only do other third party mods do this but also the base Northstar mods as mentioned before.

Did you solve this issue?

**Comment by 0neGal** [comment]
Mostly, if the parser fails to parse the `mod.json` it'll simply apply it's own bare minimum info, meaning `unknown` version number and the mod name is simply taking from the folder. It seems however that my PR has been merged for the Northstar mods as of writing this...

**Comment by Alystrasz** [comment]
There's been some discussions with [Thunderstore modding db](https://thunderstore.io/) developer, Mythic, on Discord.
He's willing to support Northstar mods: https://northstar.thunderstore.io/?ordering=last-updated

**Comment by Alystrasz** [comment]
@0neGal why can one remove Northstar needed mods?

**Comment by 0neGal** [comment]
The idea was to implement a warning in the new UI instead of working on it on the old UI, hence why you can do that currently. But it's also one of the reasons why I won't make a release available with mod support until the new UI.
