### ISSUE TITLE
bug: Viper update never completing

### ISSUE THREAD

**Issue by Vinman7122** [0neGal/viper#134]
Viper says it needs to restart and update, but when it starts to update the loading bar will never move. I let it load overnight and the bar didn't move. I'm just wondering if there is a solution for this problem, or if the update does just take that long. The image is where the loading stops, and it never moves from that spot.
![Screenshot 2022-06-14 173631](https://user-images.githubusercontent.com/50750019/173693363-f66aabdd-cda7-4891-a1a5-be9f3cdcdc9d.png)

**Comment by 0neGal** [comment]
Hmm, no it should only take a minute'ish at worst, try closing it, or restarting your computer, launching Viper again should restart the update and finish it properly, hopefully.

**Comment by Vinman7122** [comment]
> Hmm, no it should only take a minute'ish at worst, try closing it, or restarting your computer, launching Viper again should restart the update and finish it properly, hopefully.

I tried restarting Viper, as well as my computer, but neither have worked. I'm trying to update Viper to version 1.6.0, but nothing seems to be working. What else would you recommend?

**Comment by 0neGal** [comment]
Just to clarify, are you manually updating it by downloading the exe and running? Or is it Viper's auto updater?

Non-the-less, try just removing the application and re-installing, I don't know what could've caused this, your settings and alike will stay intact when re-installing. Viper itself can be uninstalled in the "Add or remove program" menu in Windows settings.

**Comment by Vinman7122** [comment]
ok, also its an automatic update, but i will reinstall, thx for the help
