### ISSUE TITLE
LSX failed

### ISSUE THREAD

**Issue by ngx200** [0neGal/viper#148]
**Describe the bug**
LSX Authentification failled at the start of Northstar

**Screenshots**
![Capture d’écran 2022-08-14 120324](https://user-images.githubusercontent.com/109249188/184532001-d13c41e1-5d3b-4a50-9eb2-49c26dff197d.png).

**Version:**
Last version of viper and northstar

**Comment by GeckoEidechse** [comment]
Try running Origin first and then launching Northstar, once Origin has fully loaded up. The issue comes from Northstar itself and shouldn't have anything to do with Viper ^^

**Comment by ngx200** [comment]
Ok, thx for the answer
