### ISSUE TITLE
bug: Installer stays on "Please wait..."

### ISSUE THREAD

**Issue by B0BERTPRIME** [0neGal/viper#167]
i recently had issues with viper so i was going to reinstall it, but when i redownloaded it and opened the setup.exe, and it just stays at this percent no matter how long i wait
![Screenshot (594)](https://user-images.githubusercontent.com/122950700/213066761-73446579-0711-4cee-b230-a62cb3cfc2b4.png)

**Comment by 0neGal** [comment]
I would make sure you've Viper uninstalled, restart the computer, and try again, if it still doesn't succeed, even after waiting a bit, I'd try to use the standalone [`.exe` file](https://github.com/0neGal/viper/releases/download/v1.6.3/Viper-1.6.3.exe), it however doesn't auto-update, hence why we don't recommend it. So I'd urge you to try to fix the installer instead.

However simply restarting and having patience should fix it, hopefully, Windows can be weird sometimes.

**Comment by 0neGal** [comment]
Given the inactivity I am closing this issue, feel free to re-open it if the issue hasn't been resolved.
