### ISSUE TITLE
bug: Unknown error when attempting to remove a mod

### ISSUE THREAD

**Issue by 1Phase1** [0neGal/viper#176]
**Describe the bug**
I'm getting a notice of an unknown error every time I try to remove the Auto Matchmaking Mod with the "remove" button. I've tried reinstalling the mod in the find mods screen and then seeing if it could be removed, but it doesn't help and the same error as before occurs. I should mention, the mod was originally installed through the FlightCore mod manager. When I uninstalled that manager and switched to Viper, the mod carried over, and now I can't remove it.

**To Reproduce**
0. Install FlightCore, then install the Auto Matchmaking Mod through Flightcore. Uninstall Flightcore without removing the mod. (I'm including this step in case it's relevant to why the mod can't be removed)
1. Navigate to the mods screen in the Viper launcher 
2. Locate the Auto Matchmaking Mod and press the "remove" button.
3. The below screenshotted error will appear. 

**Expected behavior**
The mod is removed/uninstalled as it should be.

**Screenshots**
![Screenshot 2023-02-13 201241](https://user-images.githubusercontent.com/69846246/218612573-1e26a4f0-3996-4cf5-a0b3-f3c1db03d5dd.png)

**Version:**
1.12.0

**Comment by GeckoEidechse** [comment]
> Auto Matchmaking Mod 

That's the one made by TimeIsUnending? Cause I know that the mod already has some issues on its own (breaking some Northstar functionality if used).

Can you maybe share a screenshot of how your `D:\Games on HDD\Steam\steamapps\common\Titanfall2\R2Northstar\mods` folder? ^^


Also sidenote for @0neGal, path contains spaces, Viper handles that correctly, right? ^^

**Comment by 1Phase1** [comment]
Actually, I think you just unintentionally gave me the solution to the issue. I've been looking all over for the actual folder where the mods are installed. I didn't realize that the directory at the top of the error message leads to the folder where the mods are installed. I was following the other 2 listed directories that point to my C drive and finding nothing there.

I found a folder in the Northstar mods folder listed with the Matchmaking Mod's name. Deleting that appears to have removed the mod. 

Thanks a lot, I guess that's that solved.

**Comment by GeckoEidechse** [comment]
Glad you solved it. I'm just confused now why Viper even offered to remove a non-existing(?) mod in the first place...

@0neGal you don't use `enabledmods.json` for discovering installed mods, do you? :eyes:

**Comment by 0neGal** [comment]
> **0neGal** you don't use `enabledmods.json` for discovering installed mods, do you? 👀

I do not no, I'll have to look into this myself and see what's going wrong :p
