### ISSUE TITLE
EA-APP auto-quit

### ISSUE THREAD

**Issue by H4K0N42** [0neGal/viper#182]
Include in the Setting "Automatically quit Origin", that it also closes the EA-App

**Comment by 0neGal** [comment]
I don't have a Windows installation functioning at this moment, and so I can't actually install the EA App, and so, if you don't mind, could you confirm to me what the process name of the EA App is? For Origin this would be `Origin.exe`

The simplest way to figure this out, would be to have it running, then open task manager, right click on the EA App, click `Properties`, and just take a screenshot of the window that it opens.

**Comment by GeckoEidechse** [comment]
Should be `EADesktop.exe`

https://github.com/R2NorthstarTools/FlightCore/blob/a07c8de752a3193d6e4e80fffeabde06af747fa0/src-tauri/src/lib.rs#L421-L425
