### ISSUE TITLE
feat: Open Viper normally when Titanfall2 install not detected

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#187]
Right now when opening Viper with Titanfall2 not installed or the install not being autodetected, it instantly opens a folder selection view. For a new user this is super confusing. There's nothing telling them what to do and IIRC selecting a non-Titanfall2-install folder just pops an error message and closes Viper.

Instead Viper should open normally and then prompt the user to select an install folder or behave similar to FlightCore where the _Play_ button is turned into _Select Titanfall2 game folder_ when it cannot auto-detect the install.

This (IMO) communicates more clearly to the user what needs to be done compared to opening the OS folder selection prompt.

**Comment by 0neGal** [comment]
There's actually an alert there, however it's quite possible the file picker/chooser is obscuring it, it's actually been a bug that the module (`src/modules/window.js`) to ask the renderer to open `alert()`'s never waited until the alert was closed before continuing code execution.

A commit to fix this is in upstream as of a few seconds ago ([`4e60274`](https://github.com/0neGal/viper/commit/4e60274bbefa1ddf17cb5b7589b6915254063bbe)), which implements/fixes this.

Although if this is not what you're asking for do let me know.

**Comment by GeckoEidechse** [comment]
Definitely an improvement over current situation ^^
