### ISSUE TITLE
Bug: Config file improperly formatted

### ISSUE THREAD

**Issue by swaggyboi** [0neGal/viper#189]
**Describe the bug**
When I installed and launched viper, an error comes up saying that my config file is improperly formatted, and to reset it by pressing "Ok".  I pressed ok, fully closed out of viper, then relaunched it and the same error popped up.

**To Reproduce**
I have no idea how or why this is happening, a month ago it was working just fine.

**Expected behavior**
Expected to just run like normal, I wiped my pc after installing a memory upgrade and reinstalled all of my programs.  

**Screenshots**
![image](https://github.com/0neGal/viper/assets/70466886/cc113c8d-b7f8-491b-8dbb-97299e697a49)

**Version:**
1.7.3

**Comment by 0neGal** [comment]
Does the `viper.json` file at `%%appdata%%` exist? If so, can you send me the contents of it, simply open it in Notepad.

Further, if it exists who has access to it?

This is a bug that should've been fixed very recently, so this is quite confusing.

**Comment by swaggyboi** [comment]
It does exist, for some reason there's no gamepath?  I'm using EA and tried deleting viper.json and running northstar again, thinking it would fix itself, but to no avail.
"**{"gamepath":"","lang":"en-US","nsupdate":true,"autolang":true,"forcedlang":"en","autoupdate":true,"originkill":false,"nsargs":"-multiple","zip":"C:\\Users\\anerc\\AppData\\Roaming\\vipertmp\\northstar.zip","excludes":["ns_startup_args.txt","ns_startup_args_dedi.txt"]}**" 
I don't know who has access to how, how do I check?

**Comment by 0neGal** [comment]
> for some reason there's no gamepath?

This isn't necessarily bad, this just means no gamepath is set, and if this error wasn't popping up, it'd try to search for it, and if it can't find it, it'd ask you to select it manually.




> I don't know who has access to it, how do I check?

If you can delete it without being asked for admin privileges then you're user has permissions to edit it, and hence can't be the reason, I also just confirmed this myself, that even if that was the issue, it would give a different error.

---

I'm quite unsure what's going wrong here, the content of the config file is completely valid, can you try and use the [portable version of Viper](https://0negal.github.io/viper/index.html?win-portable), and see if it has the same issues... Further, are you completely certain `v1.7.3` is the version you're currently using?

**Comment by swaggyboi** [comment]
I was able to delete it without it asking for admin privileges, and I'm certain this is 1.7.3.  I tried launching the portable version but it just doesn't open?  I see it running in task manager but the GUI isn't opening.

**Comment by swaggyboi** [comment]
Update.... I entered the correct gamepath... one error led to another, and 5 minutes of browsing through the errors others had problems with on github I eventually had to give full access of the Titanfall2 folder to my user account, even though it never asked for it.  If it helps, these were the 2 other errors I received:
![image](https://github.com/0neGal/viper/assets/70466886/1953cd3b-a718-4d1c-89b5-4635ec74dc3b)
![image](https://github.com/0neGal/viper/assets/70466886/e36d5920-4a95-44d2-a776-46b6e6eb8779)

**Comment by 0neGal** [comment]
Hmm, try killing it through task manager or restarting, it might not be exiting correctly...

Instead of starting regular, can you open `cmd.exe`, then drag the program into it and hit enter, that'll run it through `cmd.exe` and it may display some errors.

Just copy whatever it outputs...

**Comment by 0neGal** [comment]
Ah, did you fix the permissions on those folders already?

This a known bug, and better handling if missing permissions is something that's planned to be added...

**Comment by swaggyboi** [comment]
Thanks for your help, I've been trying to fix this for a week now haha.
