### ISSUE TITLE
i18n: Localize "Game is running, refusing to update Northstar"

### ISSUE THREAD

**Issue by DxsSucuk** [0neGal/viper#199]
**What feature would you like added?**
A translation for the following errors message
![image](https://github.com/0neGal/viper/assets/53257574/b45b6283-f136-4367-acf7-e75ded85dc39)

**Why should this feature be added?**
To make it easier for other users to understand what it is saying

**Additional Info**
None

**Comment by 0neGal** [comment]
I'll add the English strings for this after the next release (coming later today, hopefully), and then make a PR for the next release, localizing everything that was added in-between it and the upcoming release.

Re-requesting locale maintainers right now would add extra time before the upcoming release could be released, which would add support for the new `packages` folder.

**Comment by 0neGal** [comment]
Completely forgot about this, and now checking it, it seems it already has these strings, and they're even being used? Did you restart Viper after changing the language or similar? Because if so, it's more likely we have an issue of the language setting not being set correctly...?

**Comment by DxsSucuk** [comment]
Dont think I have? I will try to reproduce it later if thats okay.

**Comment by 0neGal** [comment]
Closing this, as it should've been fixed, re-open if it wasn't, some-magically-how :p
