### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#20]
Localisation does not work properly: some messages do not appear in target language ('fr' in my case), and some are not translated at all.

---

![Capture d’écran 2022-01-03 110819](https://user-images.githubusercontent.com/11993538/147919332-99e9d2d0-f07d-49c9-94dd-ea4036cf54d8.png)

![Capture d’écran 2022-01-03 111007](https://user-images.githubusercontent.com/11993538/147919388-51436114-0c0c-4e0b-9343-3f150aa4c1a5.png)

**Comment by 0neGal** [comment]
As for the first part, the `general.missinggamepath` I think I renamed it to just `general.missingpath` at some point and must've forgotten to do so in the lang files as well.

I've fixed that. I don't know about the other one tho. I'll have a look at it when I have the time...
