### ISSUE TITLE
bug: Viper can't update Northstar and get's stuck.

### ISSUE THREAD

**Issue by Enejuto** [0neGal/viper#202]
**Discription**
When I try to update Northstar via Viper, the Update button just gets grayed out and Viper says that it is checking for updates and leaves it at that. So I decided to try to update Northstar manually (this worked and I can launch Northstar manually). So then Viper picks it up and says how Northstar is up to date and If I launch it, it just says that it is checking for updates and stays in that limbo-like status. Done some digging around the internet yet I can't find a solution so I have came back here. I've also tried to reinstall Viper yet that doesn't work. (I own TF2 via Steam)

**To Reproduce**
1. Launch Viper
2. Attempt to Launch Northstar
3. Nothing Happens and no error message.

**Expected behavior**
I think the problem might just be something with my files (though I have verified the files via Steam) or Viper just not being able to access the internet? No clue tbh.

**Screenshots**
![image](https://github.com/0neGal/viper/assets/61654020/a3556863-9695-4549-8c53-496188d0aafa)
*As of this posts creation, Northstars most recent version is 1.17.0*

**Version:**
Viper: `v1.7.3` **|** TF2(Steam): `v.1.17.0` **|** Windows 10

**Additional Info**
There's also a problem with the Mods, however this is a minor problem and I probably cant access the menu because Viper is attempting to update Northstar.

**Comment by Enejuto** [comment]
Nevermind, I did everything except for the other setup.exe, for anyone else that has this problem, Try to download the unrecommended executeable becayse the recommended version is still stuck on 1.7.3 and not on the newer 1.8 Viper.
![image](https://github.com/0neGal/viper/assets/61654020/051e9ab9-6379-4664-ba73-2bf681d9a4b0)

**Comment by 0neGal** [comment]
> Nevermind, I did everything except for the other setup.exe, for anyone else that has this problem, Try to download the unrecommended executeable becayse the recommended version is still stuck on 1.7.3 and not on the newer 1.8 Viper.

Generally speaking this isn't quite accurate, 1.8.0 was released 12 minutes before your reply was made, Viper only checks for updates to itself on startup, and it may or may not have cached what the latest is, this would've cleared itself up after a little more time.

The portable executable doesn't auto-update and is why it's not recommended for most Windows users, it's more likely that a simple restart fixed this problem. Although, I've no clue what caused it in the first place...

Unless your installation of Viper truly isn't auto-updating then I'd prefer if your comment was edited to cross out that your recommendation to use the portable `.exe`, and a little note saying to read the comment below. As some user could stumble upon this comment, read it, and start trying to do something that may or may not fix it, but likely for a different reason entirely. Hope that makes sense...

**Comment by Enejuto** [comment]
Ah okay that makes some more sense, Ill just delete my extra comment. Yet it seems that 1.8 has fixed the problem for now, otherwise ill reopen the issue.
