### ISSUE TITLE
feat: Show window buttons whilst popups are present

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#205]
**Describe the bug**
Viper hides minimize/close buttons when going into settings.

**To Reproduce**
1. Open Viper
2. Open settings
3. Minimize/close buttons are now gone

**Expected behavior**
Window controls should always be visible regardless of current view

**Screenshots**
![image](https://github.com/0neGal/viper/assets/40122905/509697a1-af38-488e-aa5c-785d9ba46ee7)

**Version:**
`v1.8.1`

**Comment by 0neGal** [comment]
This is actually a feature I've managed to completely forget and bury in my backlog, and it's relatively easy to fix...

This isn't just the problem with the settings popup, but also the mod browser popup.
