### ISSUE TITLE
bug: launch options aren't saved

### ISSUE THREAD

**Issue by LittlePlanlessFool** [0neGal/viper#207]
**Describe the bug**
restarting the app resets the launch options to "-multiple"
launch options also aren't applied

**To Reproduce**
1. Open app
2. Click on settings
3. Add some launch options
4. Restart app/launch N*

**Expected behavior**
launch options should be saved

**Version:**
Release 1.8.1

**Comment by 0neGal** [comment]
Is there are difference between this and #206?

**Comment by LittlePlanlessFool** [comment]
yes, #206 is about editing ~~launch options~~ text boxes, this is about saving/applying launch options

**Comment by 0neGal** [comment]
This should now be fixed in the latest commit.
