### ISSUE TITLE
bug: Weird interactions for the "No such file or directory"... "R2Northstar\packages" error

### ISSUE THREAD

**Issue by CooldudePUGS** [0neGal/viper#209]
**Describe the bug**
Many users in the Discord server have been confused with an error on Viper recently

When the `mods` directory exists but `packages` doesn't, Viper gives the error properly and hitting `Install` creates a `packages` folder, which fixes it.

When `mods` and `packages` both don't exist (or a clean install), Viper installs/reinstalls Northstar (as it should), but it then gives an error (while installing Northstar) saying that the `packages` folder can't be found. If you watch the directory while you install, this is because it first extracts the `mods` folder properly, then waits a bit before making the `packages` directory, causing it to trigger the "no packages directory" error before the folder gets made

**To Reproduce**
1. Install Viper
2. Let Viper install Northstar (making sure it isn't already installed or at least the `packages` and `mods` directory don't exist)

**Expected behavior**
Viper downloads Northstar without giving an error about a missing directory that in fact exists

**Screenshots**
![image](https://github.com/0neGal/viper/assets/70904206/c238bd98-822d-4e8b-898e-2f67017c4056)
![image](https://github.com/0neGal/viper/assets/70904206/dd1272f7-973c-4b81-a564-14197ae3427e)

**Version:**
Newest, downloaded from https://0negal.github.io/viper/ right before testing

**Additional Info**
Something that Viper does causes it to create the `packages` folder after the check is done, therefore causing it to freak out and think it doesn't exist, before creating the folder properly, and letting you play

**Comment by 0neGal** [comment]
Actually, this has already been fixed in the latest version :)

**Comment by CooldudePUGS** [comment]
it seems like it was tried to be fixed, but this was all tested on 1.8.3
![image](https://github.com/0neGal/viper/assets/70904206/4445ac3b-3672-4f92-84e8-9824e592f00d)

**Comment by 0neGal** [comment]
Huh, weird, I can't seem to reproduce this, as it seems fixed for me... If possible could you run Viper in a command prompt and copy the error in it's entirety, as it seems slightly cut off, which is a different bug entirely.

It just consists of typing the full path to the `.exe` in a command prompt and it'll work, let me know if you need further help with running it there.

**Comment by CooldudePUGS** [comment]
This is the entirety of what it wrote, for reproducing make sure you remove at least both the `mods` and `packages` folder if you weren't doing that
![image](https://github.com/0neGal/viper/assets/70904206/8626fde0-56e9-456c-91c2-13a24d646f59)

**Comment by CooldudePUGS** [comment]
Using the portable exe gave the same error

**Comment by 0neGal** [comment]
Hmm, tried quickly to run it in a Windows VM, and I still, really cant find a way to reproduce this... very weird...

**Comment by 0neGal** [comment]
While I don't think this'll fix it, it's worth a go, can you try and download and attempt to reproduce it with [this build](https://we.tl/t-KrbSgEE64f)

**Comment by CooldudePUGS** [comment]
oh, no that actually did it

no error 

i will try a few more times to confirm it wasnt a one off thing

**Comment by 0neGal** [comment]
Assuming that was the fix, then I'll be closing this, as this is now patched in v1.8.4, released moments ago.
