### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#21]
For people to keep using viper, it needs to have a visually appealing interface, that allows them to do everything Northstar-related and find all information without needing to search it on Discord or Google.

---

You can assign this to me :)

![ezgif-7-0ef2baf0f8](https://user-images.githubusercontent.com/11993538/147920443-d927f742-1a28-4e2c-8c8a-34d25efa3f12.gif)

**Comment by 0neGal** [comment]
> You can assign this to me :)

As for this, currently you'll be assigned, but I'll likely jump in with changes and alike down the line if you don't mind of course.

**Comment by Alystrasz** [comment]
Sure, don't hesitate to propose stuff!

**Comment by Alystrasz** [comment]
@0neGal guess it's time for you to create a Discord account to make some noise about viper on Northstar channels :)
