### ISSUE TITLE
bug: Invalid config file (SyntaxError)

### ISSUE THREAD

**Issue by MathematicallyStupid** [0neGal/viper#210]
everytime i start the game it appears this image 
![image](https://github.com/0neGal/viper/assets/143773313/d01a8ce5-ad2f-4288-a424-e0d2429dda69)

is there anything else to do?
i've alreeady install and uninstall the program (being 1.8.1 version this one)

**Comment by 0neGal** [comment]
First of all, version 1.8.1 is not the latest, that'd be 1.8.4, your version is over a month old, however those updates shouldn't contain anything that'd fix this. But I'd still recommend updating, if you download the installer and not the portable `.exe` then it'll be able to update itself.

As for actually fixing this problem...

If clicking the OK button ("Aceptar" in your case) doesn't fix this, try and see if a file at `%APPDATA%\viper.json` exists, and delete it if so (typing `%APPDATA%` in the window that <kbd>Win+R</kbd> opens will open the app data folder, in which you can find the `viper.json` file)

That may or may not fix it, this is an error that I've never been able to reliable reproduce, hence why it even exists to begin with.

**Comment by 0neGal** [comment]
This issue is quite similar to #211 and there's a little bit more progress over in that issue, so I'll be closing this one, if you still have problems refer to that, or re-open this issue.
