### ISSUE TITLE
My mod doesn't work

### ISSUE THREAD

**Issue by Saxilesteam** [0neGal/viper#219]
Viper won't allow my mod, saying "An unknown error occurred while trying to install the mod. This may be the author's fault, and it may also by Viper's fault."

My Mod: https://northstar.thunderstore.io/package/MeepMerpMan/Saxile/

**Comment by Jigsaw159** [comment]
Also having the same issue. Switch from Thunderstore because I thought there was an issue with mods on there but now I'm thinking there's a problem in general

**Comment by JMM889901** [comment]
> Viper won't allow my mod, saying "An unknown error occurred while trying to install the mod. This may be the author's fault, and it may also by Viper's fault."
> 
> My Mod: https://northstar.thunderstore.io/package/MeepMerpMan/Saxile/

Your mod is uploaded in the wrong format and cant be read by Northstar, nor by Viper
a Thunderstore mod is a **package** containing **mods**
A Northstar *mod* must contain at least a mod.json, alongside the mod/keyvalues folders 
a Thunderstore package must contain an icon.png, a manifest.json, a readme and a folder named "mods" 
Your Northstar mod goes INSIDE this mods folder 

The correct mod format would look like [this](https://github.com/0neGal/viper/files/13063145/fixed.formatting.zip) (In order to meet GitHub file size limits I had to remove the contents of the audio folder so I wouldn't upload this without putting those files back lol

**Comment by JMM889901** [comment]
To clarify becuase the empty folders got removed by compressing to a zip, the location of your /audio folder would be in `\mods\MeepMerpMan-Saxile\mod\audio`

**Comment by 0neGal** [comment]
Just to completely clarify, this is the file structure of your mod:
```
├── README.md
├── icon.png
├── manifest.json
└── mod/
    └── audio/
        └── extra things here
```
When it instead should be as follows:
```
├── README.md
├── icon.png
├── manifest.json
└── mod/
    └── MeepMerpMan-Saxile/
        ├── audio/
        │   └── extra things here
        └── mod.json
```

And an example of what should be in the `mod.json` file:
```json
{
	"Name": "MeepMerpMan-Saxile",
	"Description": "I'm Ion Prime",
	"Version": "1.2.0",
	"LoadPriority": 0
}
```

Hope this clarifies the problem at hand and by extension solves it, I'll be closing this issue as it should be solved, if you've anymore questions or you believe it isn't solved feel free to leave more comments or re-open it if need be.

**Comment by Saxilesteam** [comment]
Thanks! Northstar seems to accept it, though I can't open it, so ill try when I get the chance.

**Comment by Saxilesteam** [comment]
alright, so the mod is accepted, but doesn't change anything. Any suggestions/solutions?
1.3.0 is the current version: [https://northstar.thunderstore.io/package/MeepMerpMan/Saxile/](url)

**Comment by 0neGal** [comment]
`1.3.0` has the correct structure as described earlier, and it is different from the other version I checked.

**Comment by Saxilesteam** [comment]
different? different good or different bad? I just need to know how to fix it, I have no clue what I am doing

**Comment by 0neGal** [comment]
`1.3.0` has the correct structure, making it different in a good way.

**Comment by Saxilesteam** [comment]
Ok, thanks for the help though
