### ISSUE TITLE
bug: Some text don't load correctly

### ISSUE THREAD

**Issue by KenMizz** [0neGal/viper#221]
**Describe the bug**
1. In Mods Menu, when clicking `Remove All` button, instead of showing the description, it shows `gui.mods.remove_all.confirm` instead.
2. In search mods browser, no results shows `gui.browser.noresults`

**To Reproduce**
1. Simply clicking `Remove All` button in Mods menu, or search some random text inside search bar.
2. bug occured.

**Expected behavior**
According to `src/langs/en.json`, `gui.mods.remove_all.confirm` should show `Removing all mods will usually require you to reinstall Northstar. Are you sure?` instead. Same as `gui.browser.noresults`, it should show `No results...`.

**Screenshots**
![image](https://github.com/0neGal/viper/assets/16635884/586e7c18-0402-444d-9e98-fa91d08e195f)
![image](https://github.com/0neGal/viper/assets/16635884/11176ef0-16f4-4fdc-8a42-e81b0c45bf8a)

**Version:**
1.9.0

**Additional Info**
Looks like a configuration error. when I change `gui.mods.remove_all_confirm` to `gui.mods.remove_all.confirm` in `src/langs/en.json`, it works again.

**Comment by 0neGal** [comment]
This is an oversight from the recently changed formatting of the localization files, I thought I'd caught them all, oh well.

Will be an easy fix however!

**Comment by 0neGal** [comment]
Got around to this, it's now fixed with the latest commit!
