### ISSUE TITLE
Flatpak: Outdated freedesktop platform being used

### ISSUE THREAD

**Issue by Jackaed** [0neGal/viper#225]
**Describe the bug**
Viper is currently using free desktop platform 21.08 on flatpak, which is EOL. Running `flatpak update` with viper installed causes a warning message to appear:

```
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.github._0negal.Viper

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github._0negal.Viper
```

**To Reproduce**
1. Install viper from flathub
2. Run flatpak upgrade
3. See above warning messages

**Version:**
Viper: v1.10.0
Titanfall 2: v2.0.11.0 

Northstar: v1.22.1
Node: v16.17.1
Electron: v22.3.25

**Comment by GeckoEidechse** [comment]
Probably best to also make an issue on https://github.com/flathub/com.github._0negal.Viper/issues ^^

**Comment by GeckoEidechse** [comment]
> Should I close this issue or should I keep both open?

I'd keep both open, not sure how often @0neGal checks the other repo, given that there's another issue on there as well that's been open for quite a while ^^"

**Comment by Jackaed** [comment]
I've tested version bumping freedesktopplatform to 23.08 and the application starts and runs as normal, so I'll make a pull on the other repo.

**Comment by 0neGal** [comment]
Funny, I got a notification for this issue, then hours later actually got around to bumping it, submitted the PR ([#22](https://github.com/flathub/com.github._0negal.Viper/pull/22)) into the repo (now awaiting build tests), then came in here to make a comment about how it should've been submitted on the Flathub repo, but I was too slow! lol

I'll close this now though, next time the bot builds the Flatpak it should be updated!

**Comment by Jackaed** [comment]
Thanks for updating it! Just was bugging me whenever I updated that I got those warnings and I decided I had nothing better to do than to try and fix it lol
