### ISSUE TITLE
GitHub rate limit

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#23]
Since Viper HTTP requests to GitHub are not authenticated, we have a rate-limit of 60 requests/hour, which is not much and can be reached quicky on certain occasions (when developing, for example...).

![InkedCapture d’écran 2022-01-04 000243_LI](https://user-images.githubusercontent.com/11993538/147989915-d5170ca7-b5ee-48e8-9171-5c064e8b71bf.jpg)

We use GitHub requests for two reasons:
- checking Viper updates
- checking Northstar updates

I think we should cache these requests' results for like 5-10 minutes.

---

Source: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by 0neGal** [comment]
Preferably just when making a request plop it in a file, say `requests.json` inside our cache dir (`app.getPath("userData")`), then inside it have something like:

```json
{
    "viperVersion": {
        "last":"<epoch time>",
        "result":"<version>"
    },
    "northstarVersion": {
        "last":"<epoch time>",
        "result":"<version>"
    }
}
```

Or a better format if there is one? 

With a format like that we can determine when the request was made and furthermore get it's data as well, achieving everything we'd need to fix this issue.

**Comment by Alystrasz** [comment]
Yeah this should be fine.

**Comment by Alystrasz** [comment]
I'll take a look at this.
