### ISSUE TITLE
bug: Error when Titanfall2 is installed on default EA App path.

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#238]
**Describe the bug**
We got a ticket on the Northstar Discord with a user being unable to install Northstar using Viper

**Screenshots**
Taken directly from their Discord ticket

![image](https://github.com/0neGal/viper/assets/40122905/89491312-f9ef-4fa0-848d-6b6f155437ce)

**Version:**
???

**Additional Info**
As hinted by the issue title, the error is most likely caused by Titanfall2 being installed on the default install path. The reason I know this, is cause this the error message the user got when trying to use FlightCore

![image](https://github.com/0neGal/viper/assets/40122905/705bc3b6-3b42-4ead-8720-85f7fa109410)
(which is triggered [by this check](https://github.com/R2NorthstarTools/FlightCore/blob/7e7c8d31bf3d84c15da72ef0bc3c8a34429b1bee/src-tauri/src/northstar/install.rs#L274-L281))

**Comment by GeckoEidechse** [comment]
Note that the ticket was since resolved by the user moving their install and switching to FlightCore so not sure if we can collect any additional info from them anymore... ^^"

**Comment by 0neGal** [comment]
Due to not using Windows I had no idea this was even an issue, out of curiosity, why does FlightCore not allow that install path? Is it some permissions issue or?

**Comment by GeckoEidechse** [comment]
It's a permission issue, yes. I don't know the exact details, whether it's an EA App thing or a `Program Files` thing but basically the default directory `C:\Program Files\EA Games\Titanfall2` is locked to EA App (and admin ofc). So user level stuff has no write access to it. (I assume to prevent programs modifying other programs logic)

Given that that is essentially what we wanna do to install Northstar, the suggested workaround is to move the game files to another location that is user writeable.
(Running as admin would also work but is not recommended as it increases the attack surface)

Note that this only affects EA App, as Origin and Steam both install into `Program Files (x86)` which does not have the same permission requirements.

**Comment by 0neGal** [comment]
Huh, weird, because there's checks in place to check for whether Viper can write into the gamepath, I guess it's only parts of it that's not writable or something...

Might've to adjust it, and possibly change the permission message to also mention that moving the install path may help.

As currently, when it was previously readable, it just tells the user to adjust the folder's permissions or select a different gamepath, and when the error happens on the initial gamepath selection it only does the latter.

**Comment by 0neGal** [comment]
This is technically complete with #249, albeit there's no specific error message, just one making an error message, a specific message should probably be added at some point...
