### ISSUE TITLE
bug: eperm: Operation not permitted

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#240]
**Describe the bug**
From a ticket on the Northstar Discord. See screenshot below

> i keep on having a error trying to press the install button on viper i cant find the location of the titanfall2 app on my files either

**Screenshots**
![image](https://github.com/0neGal/viper/assets/40122905/e0f6cc02-4c18-4d02-8ee1-26c036f07c9b)

**Version:**
_Not known yet_

**Additional Info**
Any extra info should go here!

**Comment by GeckoEidechse** [comment]
They are using EA App, my assumption is cause of the general perms issue around EA App / Program Files dir

**Comment by 0neGal** [comment]
Does the EA App only remove the write permission on the files inside it? Or is the folder itself also missing it? For the prior, I guess the files inside it should also be checked, for the latter, I wonder if the permission checking just flat out doesn't work on Windows. I've never actually tested it, so that's not entirely improbable, given that this should technically be dealt with by the permission checks that's done...

**Comment by GeckoEidechse** [comment]
Not too sure tbh. For FlightCore I just do a check for the default path and then show a corresponding warning message. Seems to work well enough where any tickets surrounding it are just about how to move the files, not the error message itself.
Don't think I even check perms lol.

**Comment by 0neGal** [comment]
Ah I see fair, I was considering doing that, however if the permission checking overall is just broken then there's still a bug present :p

Would you be able to check the permissions, or just create your own gamepath create a `Titanfall2.exe` in it, remove permissions from it, then try to get Viper to use it as the gamepath, and see if it shows a proper error or not?

**Comment by GeckoEidechse** [comment]
> Would you be able to check the permissions, or just create your own gamepath create a Titanfall2.exe in it, remove permissions from it, then try to get Viper to use it as the gamepath, and see if it shows a proper error or not?

Sadly I don't have time (or access to a Windows machine) to test atm :/

**Comment by 0neGal** [comment]
That's fine, no worries :)
I'll likely be able to get around to it, at some point™

**Comment by GeckoEidechse** [comment]
Another case reported just now

![image](https://github.com/user-attachments/assets/636e3098-907a-4f51-ada1-dd7c22114802)
