### ISSUE TITLE
bug: User unable to install mod due to connection issue despite being able to connect in browser

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#244]
**Describe the bug**
Bug report made from a ticket on Discord.

> **Describe your issue for us.**
> When I try downloading Mods i get an error message.
> **Have you read the Wiki and announcements?**
> Yes
> **What OS? What Installer (Viper/VTOL/R2MM)?**
> Windows 11, Viper v1.26.4
> **Are you trying to host a server?**
> no
> **What have you tried so far?**
> Reinstalling Viper, deleting everything then reinstalling.
![image](https://github.com/user-attachments/assets/84ab27c4-cd78-485e-bda2-cac39336d392)

![image](https://github.com/user-attachments/assets/f1a2565c-3e0f-4875-b830-1c6359d854f3)

**To Reproduce**
???

**Expected behavior**
Installing a mod should just work assuming internet connection.

**Screenshots**

![image](https://github.com/user-attachments/assets/165d74c3-f3d1-4e54-927b-c41a26ae9dfd)

![image](https://github.com/user-attachments/assets/fb16b3d0-b90a-49c6-993f-a2c216d61117)

**Version:**
???

**Additional Info**
Made by me as proxy for a ticket on Northstar Discord. Link for anyone with access to tickets: https://discord.com/channels/920776187884732556/1267446113569603699/1267446122914254901

**Comment by 0neGal** [comment]
That's a strange bug, might be related to an application specific firewall, VPN or similar, though, I'm not sure I can actually look into this without being able to reproduce it in any way... Mostly because this isn't entirely in Viper's control, best Viper can do in this situation is show a better error message :/

I will keep this open in case it's an actual issue and not just a network misconfiguration of some kind.

**Comment by GeckoEidechse** [comment]
Yeah pretty sure Viper is blocked from internet access in this case

![image](https://github.com/user-attachments/assets/28823bf8-14c3-42cf-991f-b48294772c37)


So way to go would be to have a connection check (ping cloudflare, google, <service with guaranteed uptime of your choice>) and show user  friendly error message accordingly.

**Comment by GeckoEidechse** [comment]
Definitely something blocking network connection for some applications

![image](https://github.com/user-attachments/assets/566bd04a-9fd4-4b8e-b0c0-b8799c9db001)

**Comment by 0neGal** [comment]
> So way to go would be to have a connection check (ping cloudflare, google, ) and show user friendly error message accordingly.

We actually do have a check for `navigator.onLine` albeit, it isn't always accurate, I do however realize now, it is only ever checked on startup. I'll look into making it check more frequently, and doing extra checks to remedy/help with this...
