### ISSUE TITLE
feat: Add button to disable all non-core Northstar mods

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#252]
**What feature would you like added?**
Request to add a button that disables all mod except the `Northstar.XYZ` ones

**Why should this feature be added?**
This feature is already present in FlightCore and resolves a large chunk of current tickets as the majority of them are caused by duplicate or broken mods.
![image](https://github.com/user-attachments/assets/bea79ab8-71cd-4ef4-9fee-f2665f6fa9cb)

**Additional Info**
Viper already has a kinda related button to this but it disables all mods (including the `Northstar.XYZ` ones) and also shows a warning message because of it.

![image](https://github.com/user-attachments/assets/c8f2fa69-4e91-4117-bec5-82731cca7724)

**Comment by 0neGal** [comment]
Perhaps the behavior should just be changed over to just toggling non-core mods, and entirely getting rid of the alert, solving #253 as well.

Is there any actual use and justification for a button that toggles all (including core) mods?

**Comment by GeckoEidechse** [comment]
> Is there any actual use and justification for a button that toggles all (including core) mods?

Not that I'm aware. Maybe disabling `Northstar.Custom` if you want to host a server vanilla clients can join but that's a rather rare use-case.
The only other one would be Vanilla+ but that uses a separate profile without core Northstar mods anyway....
