### ISSUE TITLE
Update on Windows

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#3]
Updating Northstar fails on Windows because you cannot create `/northstar.zip`.

![Capture d’écran 2021-12-28 122011](https://user-images.githubusercontent.com/11993538/147561185-274b4fd3-118d-402b-a36a-bd4c49b48181.png)

**Comment by 0neGal** [comment]
This is likely due to `utils.js` not updating it's `settings.gamepath` when you set it, could you try and relaunch the app, and perhaps even the output of `%APPDATA%\viper.json`?

**Comment by 0neGal** [comment]
I would also like to point out the way settings are handled under the hood is kind of dumb right now and I'll try and look at fixing it today...

**Comment by 0neGal** [comment]
This should now be fixed, essentially the bug stems from `settings.zip` not getting set/refreshed after a path is set through `utils.setpath()` relaunching the app would then set this through the initial loading of the settings. Hence the issue is only on first launch.

**Comment by Alystrasz** [comment]
I confirmed this is fixed.
