### ISSUE TITLE
fix: Possible leftover files when updating mods and NS

### ISSUE THREAD

**Issue by 0neGal** [0neGal/viper#36]
When updating NS it simply unpacks the zip in the game path, however that means if a file was removed in the core mods, when you then update the old files will still be there, instead we should therefore remove core mods when updating.

We should also do the same when installing mods, aka if a mod is detected to already be installed, remove the original then install, as to avoid those leftover files...

**Comment by Alystrasz** [comment]
Regarding mods, we gotta be careful to remove leftover files only and not configuration files, as stated in #42.
