### ISSUE TITLE
Application does not launch (standalone + installer)

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#37]
`fs-extra` is not even in `package.json` dependencies...

---

![Capture d’écran 2022-01-12 181625](https://user-images.githubusercontent.com/11993538/149189453-d1b831c8-4625-4b80-bbeb-63fca60019bc.png)

**Comment by 0neGal** [comment]
Huh, that's weird no issue when run directly it's there, I guess `electron-builder` doesn't have it by default.

I'm currently building the version with the fix...

**Comment by Alystrasz** [comment]
> Huh, that's weird no issue when run directly it's there, I guess `electron-builder` doesn't have it by default.
> 

That's because you have 'fs-extra' package in your node_modules (even if it's not listed as dependency).

**Comment by 0neGal** [comment]
It should be fixed now but if you could verify it that'd be amazing, as I built it over SSH I couldn't actually confirm it worked...

**Comment by Alystrasz** [comment]
Installer is good.
I couldn't install standalone though because Windows flagged a Trojan in viper; a friend of mine was successful in installing it though.

**Comment by 0neGal** [comment]
> Installer is good.

Wonderful.

> I couldn't install standalone though because Windows flagged a Trojan in viper

Quite typical for portable apps... Perhaps some code signing can fix it idk... I don't have much experience with it.

So your friend likely had some different UAC settings or alike.

But I'll be closing this issue :)
