### ISSUE TITLE
Use enabledmods.json to toggle mods

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#43]
According to [the documentation](https://github.com/0neGal/viper/blob/main/docs/viper.1.md#mod-support):

> Northstar itself has no filter as to what mods it loads

however this is not true, as there is `R2Northstar\enabledmods.json` which defines which mods are loaded.

So instead of moving mod folders, it would probably be better to just update the value in the JSON file. This would also show the mods as "disabled" when checking the mods page while running Northstar and when disabling a mod from within Northstar, it would also show as "disabled" in Viper.

**Comment by 0neGal** [comment]
I only recently learned about this and was planning on implementing it... I never wanted it to work in the way it does right now, fiddling with the file system is mildly dumb and tedious.

**Comment by 0neGal** [comment]
One issue of implementing this is, some mods don't properly format their `mod.json` hence getting the name of the mod can be troublesome. So we'd need to read the file and parse it ourselves.

Examples of this is placing commas in the wrong spots, trying to put comments in the files, etc etc, things not allowed, and things that break the parser. Because of this some mods wouldn't actually be able to be disabled as we can't get the name of the mod to put in the `enabledmods.json`

**Comment by GeckoEidechse** [comment]
Hmm, if we get an exception, we could fall back to using the folder name of the mod and use that in `enabledmods.json`.

Probably best if we have some logging or error detection mechanism though so in case there's a mod with incorrectly formatted `mod.json` we can notify the author.

**Comment by 0neGal** [comment]
> if we get an exception, we could fall back to using the folder name of the mod 

That's what we do for the mod name with `--mods` and or the GUI. And when doing `--mods` it even prints out an error that the mod isn't formatted properly.

It's just what we do when the folder name isn't the same as the mod name...

**Comment by Alystrasz** [comment]
Is `enabledmods.json` created by the NorthstarLauncher itself?
Can't find it on my install.

**Comment by 0neGal** [comment]
> Is `enabledmods.json` created by the NorthstarLauncher itself?
Can't find it on my install.

I was confused by this as well, it's at `R2Northstar/enabledmods.json` not `R2Northstar/mods/enabledmods.json`

**Comment by Alystrasz** [comment]
Ah, got it!
The file is not there on a fresh Northstar installation, and seems to be created only after clicking the "Reload mods" option in Northstar client itself.

**Comment by 0neGal** [comment]
> seems to be created only after clicking the "Reload mods" option in Northstar client itself.

Yes I found that out as well... We can easily generate it ourselves, I'll be assigning this issue to myself and I'll try implementing it later today...
