### ISSUE TITLE
Update logo associated with Viper

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#44]
The issue with the current logo is that it is the same as the one [NorthstarCN](https://github.com/R2NorthstarCN) uses.

![screenshot northstarcn github page](https://user-images.githubusercontent.com/40122905/149624180-424473ea-e052-4d6c-9107-c955a2568b71.png)

To avoid confusion the two projects (Viper and NorthstarCN) should probably use different logos. As NorthstarCN is closer in content to Northstar (it's just Northstar but with tweaks for the Chinese community) it makes more sense for the to use an icon that closely resembles that of Northstar.

Therefore I'd argue it would probably be best for Viper to use a different logo.

Either something else related to Northstar (the titan), like

![hover ability](https://vignette.wikia.nocookie.net/titanfall/images/5/53/VTOL_Hover.png/)

or

![flight core](https://static.wikia.nocookie.net/titanfall/images/d/dc/Flight_Core.png)

Or something related to Viper (the TF|2 character), like

![viper helmet](https://i.imgur.com/TatSI2s.png)
(Not my artwork)

That way the two projects should be better set apart and Viper would have it's own more individual look.

**Comment by 0neGal** [comment]
> Or something related to Viper (the TF|2 character)

Originally I actually did intend on making such an icon, but it was replaced by a "temporary" icon that is the current one, mostly because I'm bad at making icons...

> > I was actually planning on trying to make a flat-style icon today that looked like Viper's helmet.
> From #6

I do think NorthstarCN should keep its icon, and would prefer something related to Viper himself and not Northstar, for obvious reasons :p

So if somebody who's better at making icons would be able to make one I'll gladly change it to it...

**Comment by Alystrasz** [comment]
I like the idea of using Viper's helmet.
Maybe we can have something like Titanfall2's original icon?

![Capture d’écran 2022-01-16 220201](https://user-images.githubusercontent.com/11993538/149678985-5e474d6f-4b43-4111-b779-0549c3f6f719.png)

---

Something in this style?

![test](https://user-images.githubusercontent.com/11993538/149678989-90ba2b18-9328-4622-8bad-2ceb1bac2f55.png)

**Comment by 0neGal** [comment]
> Something in this style?

And of course with the body below it, perhaps we should then move the Northstar tab below the game tab or similar, as to have the two matching icons beside each other.

**Comment by Alystrasz** [comment]
<img src="https://user-images.githubusercontent.com/11993538/149680349-d210cfbe-1084-45a5-ab72-c59c55faaac9.png" width="200"/>

More like this?

--- 

> perhaps we should then move the Northstar tab below the game tab or similar, as to have the two matching icons beside each other.

I'm not so sure, I really think we should separate Viper stuff from game (Northstar/tf2) stuff, but you're already aware of this with the icons space story 😄

**Comment by 0neGal** [comment]
> More like this?

Precisely! Althought maybe make some space around the neck? like the original. If possible.

> I'm not so sure, I really think we should separate Viper stuff from game

I would agree, on a UX level it makes far more sense to separate, but my need to satisfy looks often comes above that, it's not a set decision, and I'll likely end up keeping the current layout...

**Comment by Alystrasz** [comment]
<img src="https://user-images.githubusercontent.com/11993538/149680970-00f9d800-6252-4fb7-8624-2b54ad395698.png" width="200"/>

--- 

Here's the GIMP project if you want to mess up with this: https://cloud.remyraes.com/s/MA46xGpftQH8zJ5 (password is `P"CnUK79ny`)

**Comment by 0neGal** [comment]
This is my version of it:
<p align="center">
<img src="https://user-images.githubusercontent.com/33325154/149681353-94ec58ab-3dea-4009-bfd1-f21acf801099.png" width="200px">
</p>

As for yours I'm not sure the gradient really fits in, not just because the original icon doesn't have it, but also because at a distance it's not visible whatsoever. When it comes to my version I'm not sure whether to keep the helmet color and background the same.

However I used the red that we use for in the app...

**Comment by Alystrasz** [comment]
I'm not a designer anyways...
Your version is sick!

**Comment by Alystrasz** [comment]
Btw, for proper crediting, I used https://www.reddit.com/r/titanfall/comments/6ndi7h/i_turned_usioells_simple_viper_graphic_into_a/ as source.

**Comment by AA-Delta** [comment]
I have a concept based on the northstar launcher logo (I'm not a designer, sorry the non centered stuff, i used an even number of pixels without realizing it could cause that)

![Mesa de trabajo 1@4x](https://user-images.githubusercontent.com/31860825/150860100-fce0a18b-f341-42ae-b324-80b4bc77aa48.png)

**Comment by 0neGal** [comment]
> I have a concept based on the northstar launcher logo

That actually looks really good! 

> maybe you could even include the NorthstarCN to avoid another fork (it seems that they have already forked the Viper launcher) maybe with a region selector on the initial launch.

We natively support translations and localizations, it's all up to them adding them.

**Comment by AA-Delta** [comment]
> I have a concept based on the northstar launcher logo (I'm not a designer, sorry the non centered stuff, i used an even number of pixels without realizing it could cause that) It would fit with the launcher icons, maybe you could even include the NorthstarCN to avoid another fork (it seems that they have already forked the Viper launcher) maybe with a region selector on the initial launch.
> 
> ![Mesa de trabajo 1@4x](https://user-images.githubusercontent.com/31860825/150860100-fce0a18b-f341-42ae-b324-80b4bc77aa48.png)


Here's the Illustrator .ai if you want to use it
(the color of choice was because of viper's visor, btw)

[NS.zip](https://github.com/0neGal/viper/files/7928909/NS.zip)

**Comment by AA-Delta** [comment]
> > I have a concept based on the northstar launcher logo
> 
> That actually looks really good!
> 
Thank you!
> > maybe you could even include the NorthstarCN to avoid another fork (it seems that they have already forked the Viper launcher) maybe with a region selector on the initial launch.
> 
> We natively support translations and localizations, it's all up to them adding them.

I meant to include the NorthstarCN launcher builds, not the translation of the Viper Launcher. idk if that is too much work and if it's better if they maintain their own version of it. that way you would have the Viper Laucher logo, the Northstar Launcher logo and the NorthsarCN Fork logo all in one laucher, it would look nice and would avoid having two version of Viper to download two versions of Northstar

**Comment by AA-Delta** [comment]
> > I have a concept based on the northstar launcher logo
> 
> That actually looks really good!
> 

Thank you!

> > maybe you could even include the NorthstarCN to avoid another fork (it seems that they have already forked the Viper launcher) maybe with a region selector on the initial launch.
> 
> We natively support translations and localizations, it's all up to them adding them.

What I meant is that you could implement downloading the normal Northstar launcher and the NorthstarCN fork at the same time (not talking about translations) that way you could have the final Viper logo (looking similar to the NS launcher like the design I made) besides the Normal NS Launcher and the Chinese Fork logo looking all good and you could avoid a fork of Viper that can cause more segmentation. (i know this is a logo issue, but I'm thinking if you implement that function) and the CN fork dev team can just commit to the viper's repo instead for downloading their fork of Viper.

**Comment by AA-Delta** [comment]
I made some changes, and in gray scale with orange "shadows", here's the zip with the .ai files too!

>[Viper Logo.zip](https://github.com/0neGal/viper/files/7933787/Viper.Logo.zip)

With neck:
![Mesa de trabajo 1WN](https://user-images.githubusercontent.com/31860825/150983208-5af43e70-abce-4500-8106-10a8079930ab.png)

Without neck:
![Mesa de trabajo 1WON](https://user-images.githubusercontent.com/31860825/150983249-f74abb77-c51d-4b10-b34c-f3df266a78db.png)

With neck grayscale:
![Mesa de trabajo 1WNGS](https://user-images.githubusercontent.com/31860825/150983284-43713577-3453-44d7-b56a-290839a887fc.png)

Without neck grayscale
![Mesa de trabajo 1WONGS](https://user-images.githubusercontent.com/31860825/150983301-7d69a138-6ffc-4871-ae01-d6eb7ea2ad28.png)

**Comment by 0neGal** [comment]
Orange without neck is the one I prefer of those 4...

**Comment by AA-Delta** [comment]
### Here's a preview of the icon in use with the launcher
![image](https://user-images.githubusercontent.com/31860825/151044686-c5c8a2fa-88b3-4410-8b1f-35287e484efb.png)

>#58 also showing the spanish locale working and looking ok

**Comment by AA-Delta** [comment]
I corrected a defect in the right side of the helmet in the logo:

![512x512](https://user-images.githubusercontent.com/31860825/151167645-c6a13416-53b3-4054-bbfa-52985417828c.png)

How should i go about trying to help with the logo? should i just keep updating progress here? should i make a PR with the logo and vector?

**Comment by 0neGal** [comment]
Given that there's no actual code being changed I'd much prefer if you just let me know when you're where you feel the logo is done, and of course feel free to post progress... When done I'll make the PR updating all the assets to the new logo :)

**Comment by AA-Delta** [comment]
I'm going to upload the final files in a moment, but first i want to ask if i should license it unde CC SA, Public domain or just don't bother at all with licensing?

**Comment by 0neGal** [comment]
> ... but first i want to ask if i should license it unde CC SA, Public domain or just don't bother at all with licensing?

Given that it's inside this repository, it automatically inherits the repo's license (GPLv3), hence no license, I'm assuming this is some metadata Illustrator allows to put on the image? In that case no license.

Generally contributing to an open source repository you automatically accept that your work will be submitted under the repo's license. Anything we can't put under the license we have to credit and specify (See the Credits section)

Hope that makes sense...

**Comment by AA-Delta** [comment]
Ok, i asked because i thought that gpl just covered code and not assets.
If you want to change anything, just tell me and i'll be glad to make the changes!

![512x512](https://user-images.githubusercontent.com/31860825/151404954-3cdea776-9649-4481-9691-1d8fe2c4c909.png)

## Here's the final version

- Corrected centering and symmetry of the icon
- Fixed Viper's helmet glow
- Added a shadow to Viper's helmet to highlight it better, and to give a sense of light from above in the icon

## Here's the zip with the files

[Viper Icon.zip](https://github.com/0neGal/viper/files/7952367/Viper.Icon.zip)
