### ISSUE TITLE
feat: Skin manager

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#48]
![Capture d’écran de 2022-01-17 08-15-01](https://user-images.githubusercontent.com/11993538/149724477-eb2eb887-0a2b-42c0-85f6-86c2930c6d52.png)

---

Translation:
_Hello, sorry to bother, but if Viper has no skin manager, I think it would be a good idea to add one._

**Comment by 0neGal** [comment]
I wanted to do this as well, the problem lies in that (from what I know) there's no skin installer which has a CLI tool or alike, along with that is cross-platform. The best we can do is VPK skins with RSPN-VPK, which has both those.

**Comment by 0neGal** [comment]
I think I'll write my own Node module to apply DDS files/skins, which we'll then use in Viper. As for VTF skins, I'll consider doing something for that as well.

**Comment by B-bup** [comment]
can you use this https://github.com/zxcPandora/Titanfall2-SkinTool ?

**Comment by 0neGal** [comment]
I've already looked at it, however unless it has a CLI interface we can't, and even then it'd only work on the Windows version. And without CLI there's no easy way to integrate it.

Overall it'd be more seamless to make our own.

**Comment by Alystrasz** [comment]
I don't know at all how skins work.
Could we visualize them in Viper (using three.js for example : https://threejs.org/examples/?q=dds#webgl_loader_texture_dds) ?

**Comment by 0neGal** [comment]
Theoretically yes, tho I do believe we'd need to also have the models as to have something to put the texture on, which we obviously can't distribute...

**Comment by Alystrasz** [comment]
Can't we find free models matching the official ones?

**Comment by 0neGal** [comment]
We could but they'd have to be more or less the exact dimensions and so on. It would be possible in theory tho.

**Comment by 0neGal** [comment]
I think considering the fact that a lot of skin designers seem to be moving to a format of Northstar mods over manual DDS and VPK applying of skins, we should consider closing this issue, as skins can already be installed through the mod browser.

I am likely going to add a way to filter mods, as to make it easier to find skins specifically, making this issue redundant, I am going to leave the issue open for now however.

**Comment by Alystrasz** [comment]
While adding new skins, what's the difference between modifying VPK files and mods installing?

**Comment by GeckoEidechse** [comment]
This issue can be closed. DDS skins are deprecated in favour of rpaks which can be installed as simple mods, requiring no changes to the mod-manager.
