### ISSUE TITLE
Sign Windows releases of Viper

### ISSUE THREAD

**Issue by uberfig** [0neGal/viper#59]
**What feature would you like added?**

-would it be possible to get the launcher signed for windows

**Why should this feature be added?**

-getting viper signed would make it much easier to install for those who are new to modding and have an overzealous antivirus 

**Additional Info**

-I'm not sure this is really feasible, however another option could be to also distribute the launcher on itch so it can be run in itch's secure environment

**Comment by 0neGal** [comment]
Is this on the installer or on the standalone executable? I haven't heard anyone have an issue with the installer...

**Comment by uberfig** [comment]
when I first installed viper (before northstar) windows defender wasn't too happy about it and said that it was not signed. It wasn't a big deal but it was a bit annoying

**Comment by AA-Delta** [comment]
> Is this on the installer or on the standalone executable? I haven't heard anyone have an issue with the installer...

I had a problem in a VM with an outdated version of Windows  Defender. Detected Viper as a threat, both the official builds and the build I made for testing the translation and the icon. With an updated AV database it should not happen. Besides that incident, windows shouldn't bother you with certificates/signing unless you need to acces a folder with admin rights, then the UAC prompt should tell you that it isn't signed. And for what it matters, Northstar isn't signed either for what i know , so no point in signing Viper just yet imo.

**Comment by Alystrasz** [comment]
It does cost some money, unfortunately...
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by 0neGal** [comment]
I thought as much, and considering it's very few, from what I know? That have issues with the installer/setup version, I don't see it as something that we actually need.

**Comment by uberfig** [comment]
This isn't really that important, and I will test and see if there are ways to circumvent this situation with something like itch.io
