### ISSUE TITLE
ns_startup_args.txt is excluded and not restored

### ISSUE THREAD

**Issue by microraptor** [0neGal/viper#61]
**Describe the bug**
Northstars's `ns_startup_args.txt` is moved to `ns_startup_args.txt.excluded`, when checking for Northstar updates. However, if Northstar is already up to date the file is not restored and there is no `ns_startup_args.txt`, only `ns_startup_args.txt.excluded` remains, which Northstar ignores.

There is the same issue with  `ns_startup_args_dedi.txt`.

**To Reproduce**
Check for Northstar updates within Viper, when Northstar is already on the latest version. There will be no more `ns_startup_args.txt` in the game path.

**Expected behavior**
Don't move `ns_startup_args.txt`, if no update is found.

**Comment by 0neGal** [comment]
Another fun but sort of relating to this, if you interrupt an update your `ns_args` will be left as their excluded versions.

Hence we should also check for that and rename them back on startup.
