### ISSUE TITLE
feat: Set custom launch arguments in the GUI

### ISSUE THREAD

**Issue by microraptor** [0neGal/viper#62]
**What feature would you like added?**
It would be nice to set a list of custom launch arguments within the Viper GUI. These are then appended to `ns_startup_args.txt` on every Northstar update and also are passed on as command parameters, when starting vanilla TF2.

**Why should this feature be added?**
The convenience of not having to manually edit `ns_startup_args.txt` after every update or using a shortcut outside of Viper to launch vanilla TF2 with custom arguments.

**Additional Info**
These launch arguments are supported but TF2/Northstar:
[pcgamingwiki.com](https://www.pcgamingwiki.com/wiki/Titanfall_2#Command_line_parameters)
[Northstar-Wiki](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/launch-arguments)
I personally find these arguments useful:
-novid
-high
-noborder
+cl_showfps 1

**Comment by microraptor** [comment]
Actually, it might be convenient to have launch arguments as GUI settings with check boxes and stuff.

**Comment by 0neGal** [comment]
Actually, I've already sort of thought of this, tho it includes an overall settings page.

> Actually, it might be convenient to have launch arguments as GUI settings with check boxes and stuff.

Likely just have an input, an instead link to a page with more settings...

**Comment by GeckoEidechse** [comment]
Interesting question:
Should this just end up editing `ns_startup_args.txt` or only run those arguments when starting Northstar via Viper?

(I'm tending towards the former to maintain better compatibility with plain Northstar)

**Comment by 0neGal** [comment]
I was thinking just modifying the `ns_startup_args`, but to be more precise, I'd love to have a UI where you can type in the arguments, but you also have a recommended arguments along with explanation of what they do.

As for the UI itself, the whole typing in could be cool if it looked akin to the way you edit topics on a GitHub repo, if you've ever seen it:

![image](https://user-images.githubusercontent.com/33325154/152254473-03434724-bfe9-4950-aa60-9a3b03ab424f.png)

Where you simply type it, then making a space adds it as one of the arguments. I'm not aware of any positional arguments that can be added so this should be fine?

**Comment by GeckoEidechse** [comment]
Well there are arguments like `+cl_showfps 1` where naturally the `1` needs to be the value directly after `+cl_showfps` for it to works.

**Comment by 0neGal** [comment]
> Well there are arguments like `+cl_showfps 1`

Does all positional arguments start with `+`? And all other with `-`?

If so that'd make this still doable.

**Comment by GeckoEidechse** [comment]
Going through my old startup commands it seems no, `-language English` is one of the exceptions I found.
Also because a single positional argument would be too easy, there's also `+bind "F5" "toggleconsole"`

As an example, old launch arguments I used before moving all convars into a separate config file:
```
-high +cl_showfps 1 +cl_showpos 2 -novid +mat_disable_bloom "1" +mat_sun_color "3 3 3" +exec autoexec.cfg
```

**Comment by 0neGal** [comment]
> ... it seems no, `-language English` is one of the exceptions I found.

In that case I guess we'll just have to do a normal input...

**Comment by Alystrasz** [comment]
I'd like to work on this.
@0neGal, may I?

**Comment by 0neGal** [comment]
This and the Linux launch issue is one of the few ones that I'd like to work on, I already have a decent idea of how it'd look and so on. Feel free to take any other issues tho...
