### ISSUE TITLE
feat: Improve install experience for Github novices

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#63]
**What feature would you like added?**
Instead of linking to releases in the README, link directly to the install files, i.e. something like

```
# Install
[Windows](https://github.com/0neGal/viper/releases/download/v1.1.0/Viper-Setup-1.1.0.exe) | [Windows (portable)](https://github.com/0neGal/viper/releases/download/v1.1.0/Viper-1.1.0.exe) | [Linux (AppImage)](https://github.com/0neGal/viper/releases/download/v1.1.0/Viper-1.1.0.AppImage) | <the rest of the links>
```

which would be rendered as

***
# Install
[Windows](https://github.com/0neGal/viper/releases/download/v1.1.0/Viper-Setup-1.1.0.exe) | [Windows (portable)](https://github.com/0neGal/viper/releases/download/v1.1.0/Viper-1.1.0.exe) | [Linux (AppImage)](https://github.com/0neGal/viper/releases/download/v1.1.0/Viper-1.1.0.AppImage) | \<the rest of the links\>
***

&nbsp;

**Why should this feature be added?**
I already had multiple people ask me how to download Viper when I linked them the repo. In particular they asked which version to download when going to the release page via the link in the README. By offering a more direct download button this sort of friction could be resolved or at least reduced.

&nbsp;

**Additional Info**
Perhaps instead of links even use some sort of badges for the different platforms to make it especially easy for someone to find the download link for their platform.

Example:
[![image](https://user-images.githubusercontent.com/40122905/152256376-3f9c9e96-1c63-43f8-9305-5d609536eb77.png)](https://github.com/zoeyfyi/TeX-Match#downloads)

**Comment by 0neGal** [comment]
I think the layout is simple, however it doesn't explain how the portable version can't auto update, I think having a big install button that links to the setup exe might be useful. And then having a table of install links with explanations as to what each one is for would be more preferable.

**Comment by 0neGal** [comment]
I tried my hand at making something better [here's](https://github.com/0neGal/viper/blob/ee309d8305f006f89ea4bec2bc3c03d3f8c1dc2c/README.md) the first draft. Feel free to suggest changes ofc...

**Comment by 0neGal** [comment]
I added a Windows logo to the download button, to sort of signify what exactly the user is downloading ([view it here](https://github.com/0neGal/viper/blob/210d31633abd39c0d2fc751b68d9e6627690adeb/README.md))

**Comment by GeckoEidechse** [comment]
Looks nice :D
