### ISSUE TITLE
bug: After checking for new Northstar versions the "ns_startup_args.txt" file gets excluded.

### ISSUE THREAD

**Issue by PopTartsWasTaken** [0neGal/viper#74]
**Describe The Bug**
After Clicking the "Check for updates" button in the Northstar tab, "ns_startup_args.txt" is set back to its default filename "ns_startup_args.txt.excluded"

**To Reproduce**
1. Navigate to Northstar tab in Viper
2. Click the "(Check For Updates)" button
3. When you start the game all of your startup arguments will not load.

**Expected behavior**
The startup args file should not be affected by the checking for updates button.

**Screenshots**

**Version:**
v1.2.1

**Additional Info**
Any extra info should go here!

**Comment by 0neGal** [comment]
I do believe #73 fixes this, but I'm not entirely sure if it exactly fits what you're describing, keep in mind, it is not currently in any release yet. Feel free to re-open if it doesn't actually fix it.
