### ISSUE TITLE
Anti-Virus found a Trojan in the /Local folder

### ISSUE THREAD

**Issue by NeighbourVadim** [0neGal/viper#78]
### Describe the problem:
The Anti-Virus software "Kaspersky" found a Trojan in the C:\Users\ ---\AppData\Local\viper-updater\pending folder
File name: Viper-Setup-1.2.2.exe
It didn't ping when installed
A random scan was started and this popped up
Viper is installed for about 1-2 weeks now

### Screenshot of the Anti-Virus 
![Screenshot 2022-02-17 105706](https://user-images.githubusercontent.com/99873830/154451697-30ea2166-4e12-49b0-9e24-32b85178a607.png)

### Link to virustotal.com:
https://www.virustotal.com/gui/file/b39cf3b4fa32ac97a92d4fa4aa5439c7613c60e6b24540c38b0f65fcfc42a186/detection

**Comment by 0neGal** [comment]
This is a false positive which we can't really do anything about. Signing Viper is expensive and tedious.

**Comment by NeighbourVadim** [comment]
understandable
have a nice day

**Comment by 0neGal** [comment]
I will say as a last thing, if anybody knows what piece of code triggered the false positive, feel free to open a PR. I personally have no clue and won't try and spend time on it, considering it's only one AV checker which is set off. It may also be part of the NSIS installer and not our code, so I don't know.

But besides that this issue will stay closed.
