### ISSUE TITLE
feat: Drag Mod file into viper launcher to install mod

### ISSUE THREAD

**Issue by PopTartsWasTaken** [0neGal/viper#80]
**What feature would you like added?**
We should be able to drag a mod file into the Viper window to install the mod like you would with the install mod button.

**Why should this feature be added?**
More convenient to install mods from the Discord, or any mods that arent on ThunderStore.

**Additional Info**
Feel free to put anything here or delete it if not relevant.

**Comment by Alystrasz** [comment]
What's great with Thunderstore is that it imposes a format for mods.
Rather than implementing external mods installation, I'd suggest porting said mods to Thunderstore.

**Comment by 0neGal** [comment]
> I'd suggest porting said mods to Thunderstore.

It can still be used when testing mods etc, hence this'll still be implemented.

**Comment by Alystrasz** [comment]
That's the same debate you got with laundmo over there: https://github.com/0neGal/viper/pull/50
Testing mods (during development I suppose) should be done directly against Thunderstore API, to ensure mod structure is correct; you don't want viper to validate mods that will not be uploadable to thunderstore.

**Comment by 0neGal** [comment]
I don't see how those have anything to do with each other, we do show a toast for when a mod doesn't follow Thunderstore standards. There's no difference between the user dragging the mod in and using the install button, one is just less tedious.

**Comment by Alystrasz** [comment]
For viper, the whole point of using Thunderstore is to avoid developing several ways of installing mods.

Since in the end, mods will be installed directly by Northstar itself, mods validation shouldn't be done by clients but by the API itself.

**Comment by 0neGal** [comment]
I still don't see how this relates to this issue at all.
