### ISSUE TITLE
bug: Cannot build Viper

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#86]
**Describe the bug**

**To Reproduce**
1. Pull viper repo
2. Run `npm i`

**Expected behavior**
All dependencies are installed.

**Screenshots**
![Capture d’écran 2022-02-21 095117](https://user-images.githubusercontent.com/11993538/154920349-086b18f2-e65d-4c93-9a65-b221c79955ee.png)

**Version:**
1.2.3

---

Maybe this has something to do with [dmg-license](https://www.npmjs.com/package/dmg-license) dependency being deprecated (used in electron-builder?).

**Comment by 0neGal** [comment]
Not only do I not get this error, but the `package-lock.json` states it is only an optional dependency of `dmg-builder`, which is a dependency of `electron-builder` as you noticed as well. 

```json
"node_modules/dmg-builder": {
	"version": "22.14.5",
	"resolved": "https://registry.npmjs.org/dmg-builder/-/dmg-builder-22.14.5.tgz",
	"integrity": "sha512-1GvFGQE332bvPamcMwZDqWqfWfJTyyDLOsHMcGi0zs+Jh7JOn6/zuBkHJIWHdsj2QJbhzLVyd2/ZqttOKv7I8w==",
	"dev": true,
	"dependencies": {
		"app-builder-lib": "22.14.5",
		"builder-util": "22.14.5",
		"builder-util-runtime": "8.9.1",
		"fs-extra": "^10.0.0",
		"iconv-lite": "^0.6.2",
		"js-yaml": "^4.1.0"
	},
	"optionalDependencies": {
		"dmg-license": "^1.0.9"
	}
},
```

It being deprecated shouldn't affect you. Furthermore, when I re-install from the bottom up, it never gets installed by npm. So for some reason it doesn't get passed as optional for you.

**Comment by Alystrasz** [comment]
I think it's related to my `npm` version (v6), which struggles with lockfile version 2 (as displayed on my screenshot).

After updating to `npm v8.3.1`, I had no problem installing dependencies. 
Maybe we should mention that somewhere?

**Comment by 0neGal** [comment]
> Maybe we should mention that somewhere?

I'm not sure that's so important, also considering there's a warning directly saying what's wrong (even tho we both managed to miss it), so I don't think it's something that really matters. How did you even manage to use npm 6 this time, but npm 7 in the past?

**Comment by Alystrasz** [comment]
For professional reasons, I've been using node version 14 (shipped with npm 6), which is still supported: https://nodejs.org/en/about/releases/

I build my packages for node v14 and v16 at the same time: in this case, lockfile warning does not prevent package from being built for both versions with npm 6.

(I use several computers to work, and it seems they have different npm versions without me noticing it...)

**Comment by 0neGal** [comment]
Ah, I see, didn't know npm 6 had LTS releases, but ig it makes sense considering how big a difference lockfile v2 has over v1 (iirc v2 came with npm 7), and there's probably even more breaking changes for some use cases.

I think unless we get more reports of people not noticing npm 7 and up is required we'll leave it like it is, otherwise we can add a tiny *"notice"* in the **Development** section of the README.
