### ISSUE TITLE
feat: Deprecate ns_version.txt in favour of version resource specified by in Northstar executable

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#91]
**What feature would you like added?**

Instead or relying on its own version flag for the installed Northstar version, Viper should instead read-out the version provided in `mods.json` of the default Northstar mods (`Northstar.Custom`, `Northstar.Client`, ...) as well as the [version resource field](https://github.com/R2Northstar/NorthstarLauncher/blob/main/LauncherInjector/resources.rc#L63-L94) in the `NorthstarLauncher.exe`.

Reading out version resource of a current release of `NorthstarLauncher.exe` using `exiftool`:

```
$ exiftool NorthstarLauncher.exe 
ExifTool Version Number         : 11.88
File Name                       : NorthstarLauncher.exe
Directory                       : .
File Size                       : 60 kB
File Modification Date/Time     : 2022:02:18 16:39:04+01:00
File Access Date/Time           : 2022:02:28 14:29:27+01:00
File Inode Change Date/Time     : 2022:02:28 14:29:27+01:00
File Permissions                : rw-rw-r--
File Type                       : Win64 EXE
File Type Extension             : exe
MIME Type                       : application/octet-stream
Machine Type                    : AMD AMD64
Time Stamp                      : 2022:02:18 17:38:29+01:00
Image File Characteristics      : Executable, Large address aware
PE Type                         : PE32+
Linker Version                  : 14.30
Code Size                       : 29184
Initialized Data Size           : 56832
Uninitialized Data Size         : 0
Entry Point                     : 0x7070
OS Version                      : 6.0
Image Version                   : 0.0
Subsystem Version               : 6.0
Subsystem                       : Windows command line
File Version Number             : 1.5.1.0
Product Version Number          : 1.5.1.0
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Windows NT 32-bit
Object File Type                : Executable application
File Subtype                    : 0
Language Code                   : English (British)
Character Set                   : Unicode
Company Name                    : Northstar Developers
File Description                : Northstar Launcher
File Version                    : v1.5.1
Internal Name                   : NorthstarLauncher.exe
Legal Copyright                 : Copyright (C) 2021
Original File Name              : NorthstarLauncher.exe
Product Name                    : Northstar Launcher
Product Version                 : v1.5.1
```

**Why should this feature be added?**
Currently installing Viper after Northstar means that Viper will detect the current version as unknown. Similarly manually updating Northstar without Viper will result in Viper re-updating Northstar. Using the version fields in the core mods and launcher instead of its own text file means that Viper can more accurately detect the currently installed version of Northstar.

Additionally this reduces the number of added files to the Titanfall2 directory by 1 ¯\\\_(ツ)\_/¯

**Additional Info**
Both version fields (Launcher and Mods) are set via CI when creating a release of Northstar (since version `v1.5.0` of Northstar) and therefore should accurately reflect the currently installed Northstar version.

Conversely older versions of Northstar have a mismatch between launcher and mods (`v1.4.0` had mods at `1.1.0` while launcher was `1.4.0`) or did not correctly reflect Northstar version at all (when we created the patch release `v1.4.1` with backported fixes we didn't have CI setup properly yet and forgot to update the version field in the launcher resulting in it saying `1.3.0`)

Additionally viper would also need to be able to handle release candidate version numbers as well, for example [`v1.5.1-rc2`](https://github.com/R2Northstar/Northstar/actions/runs/1859242387) has launcher version as

```
$ exiftool NorthstarLauncher.exe 
ExifTool Version Number         : 11.88
File Name                       : NorthstarLauncher.exe
Directory                       : .
File Size                       : 60 kB
File Modification Date/Time     : 2022:02:17 14:40:32+01:00
File Access Date/Time           : 0000:00:00 00:00:00
File Inode Change Date/Time     : 2022:02:28 14:47:13+01:00
...
Company Name                    : Northstar Developers
File Description                : Northstar Launcher
File Version                    : v1.5.1-rc2
Internal Name                   : NorthstarLauncher.exe
Legal Copyright                 : Copyright (C) 2021
Original File Name              : NorthstarLauncher.exe
Product Name                    : Northstar Launcher
Product Version                 : v1.5.1-rc2
```

and the core mods as:

```json
{
  "Name": "Northstar.Custom",
  "Description": "Custom content for Northstar: extra weapons, gamemodes, etc.",
  "Version": "1.5.1-rc2",
  "LoadPriority": 1,
...
}
```

**Comment by GeckoEidechse** [comment]
What came to mind, is that if implemented viper should also receive a "force-update button", to allow for fixing cases where a user manually installed Norhtstar in the correct location but somehow messed something up, is told to use viper as a remedy, viper detects the current install and doesn't update it, leaving the user's issue unresolved.

Forcing an update by deleting `ns_version.txt` would then also no longer be possible, increasing the need for some force-update functionality.

**Comment by GeckoEidechse** [comment]
> There are multiple issues, EXIF will need extra dependencies, no clue if there's even a Node module that does support retrieving the info we need, most are made for images...

`exiftool` was just an example I used to read out version resource. There's probably a better way to do via some NPM package. Quick websearch "_windows exe version resource nodejs_" resulted in [resedit-js](https://github.com/jet2jet/resedit-js) but that seems to be more targeted at editing resource fields instead of just reading them. ^^

> And more importantly, is the `rc2` part of `v1.5.1-rc2` something that are in release builds, or is this just on your testing builds

It's only in testing builds. Although those testing builds are public (behind login-wall). Basically what I'm trying to say is that viper might want to be able to handle such cases without crashing :P

>  But even if it isn't in release builds, we still have the issue of what happens when the core mod we use to get the version is removed.

The way I'd suggest approaching it is checking the version of core mods via some form of regex, i.e. check version field of all mods that start with `Northstar.*` [1] and check their version number. Compare with version resource of launcher and take the lowest value as the currently installed [2].
Alternatively only look at the version of the launcher as I'd consider this the most core part. [3]
Alternatively only look at core mods version using method described above [4]

> As for mods, what do we do if the user removes a core mod?

Just checking all `Northstar.*` mods also covers this.

***

[1] Generally `Nortstar.XYZ` as mod name is reserved for core mods only, although this isn't a hard requirement on thunderstore yet.
[2] This will however report `v1.4.0` as `v1.0.0` for example due to lack of synchronisation of version numbers in older releases but as Viper then auto-updates to `v1.5.1` which known to have version numbers synced, I'd consider it a non-issue.
[3] This is a reminder that really ancient versions of NorthstarLauncher do not have this field yet, might require some exception handling in case version resource is missing.
[4] This always had a version field so no edge case handling there.

**Comment by 0neGal** [comment]
>> As for mods, what do we do if the user removes a core mod?
>
> Just checking all `Northstar.*` mods also covers this.

What I meant is, what if a user uninstalls all core mods...

> `exiftool` was just an example I used to read out version resource. There's probably a better way to do via some NPM package. Quick websearch "_windows exe version resource nodejs_" resulted in [resedit-js](https://github.com/jet2jet/resedit-js) but that seems to be more targeted at editing resource fields instead of just reading them. ^^

Had no clue about "windows version resources", as a Linux user, so I just assumed since you were using EXIFTool, that it was specifically EXIF data... I'll try to find one that'll be able to do the job.

Generally I still think the version resource is better than looking at mods, not just because of the questions I posed, but also because of how much more complicated it'll be to implement, with no real advantage, already looking at your comment, it's clear it'll take far more code and we'll need to cover far more edge cases. Compared to just reading the version resource.

**Comment by Alystrasz** [comment]
Actually, since Northstar is now released on Thunderstore (all info on latest Northstar version are visible to Viper from [here](https://northstar.thunderstore.io/c/northstar/api/v1/package/69f57005-ea87-4846-8775-3d42283b4f5e/)), we could just 100% rely on it to check Northstar version and install latest releases, don't you think?

As @GeckoEidechse said, to check locally installed version, we'd just have to check `R2Northstar/mods/Northstar.*/mod.json` version.

**Comment by 0neGal** [comment]
> Actually, since Northstar is now released on Thunderstore (all info on latest Northstar version are visible to Viper from [here](https://northstar.thunderstore.io/c/northstar/api/v1/package/69f57005-ea87-4846-8775-3d42283b4f5e/)), we could just 100% rely on it to check Northstar version and install latest releases, don't you think?

We could, but I don't think we should. There's no good reason to download from GitHub, and retrieve version numbers from Thunderstore, it would then be possible for the versions to not be the same causing problems, and generally there's no reason to make extra requests and so on. In short, no real advantage.

> ... to check locally installed version, we'd just have to check `R2Northstar/mods/Northstar.*/mod.json` version.

Overall this seems like the best solution, as I've been unable to find any NPM packages that allow us to read the version resource of the `.exe`.

I'll have a look at implementing this some time this week hopefully.

**Comment by 0neGal** [comment]
> We could use Thunderstore both for version checking AND northstar installation/update process; I agree with you that doing X with GitHub and Y with Thunderstore is nonsense.

That is a possible solution, however I still don't see much of a reason to do it, unless the NS Team randomly decides to no longer make GitHub releases and only releases on Thunderstore, which would not only make manual installation more annoying, but break many of the various launchers/managers.

Unless there's a clear advantage to using Thunderstore I don't see a reason to switch to it.

**Comment by Alystrasz** [comment]
I'm only suggesting here that Thunderstore could allow us to:
* get rid of `ns_version.txt` (which is the initial point of this issue)
* install Northstar on a Titanfall folder
* Compare local/distant versions to check if an update is needed, and install it if needed

All of this without adding any dependencies at all :)

**Comment by 0neGal** [comment]
I'm still not sure what the advantage is, we can already do all those, as the `mod.json` is included in the GitHub release as well, there wouldn't be a single difference. An idea would be to implement an option for selecting whether you want NS from Thunderstore or GitHub, tho without a difference there's not much reason to add that.

**Comment by 0neGal** [comment]
Out of curiosity, which mod folder would be best to read from? I'm not too familiar with what `Northstar.Client` and `Northstar.Custom` does, but I'd assume client is to connect to the servers, and custom is for various gamemodes, and custom servers being hosting servers or something similar.

If someone knows whether there's any reason to read from one over the other lmk, I'd assume @GeckoEidechse would know more about this...

**Comment by 0neGal** [comment]
> Should we check all mods' versions, in case somebody deletes one of them?

We could do that, but how would we handle which version to accept if one mod has a different version number than the other?

**Comment by Alystrasz** [comment]
I summon @GeckoEidechse to answer this 😄

**Comment by Alystrasz** [comment]
> Northstar mods will have same version number 

If this statement is correct and there are versions mismatchs, we could just consider the installation as corrupted, and reinstall Northstar from zero.

**Comment by 0neGal** [comment]
> ... we could just consider the installation as corrupted, and reinstall Northstar from zero.

Honestly that does seem like a solution...

**Comment by GeckoEidechse** [comment]
> Out of curiosity, which mod folder would be best to read from? I'm not too familiar with what `Northstar.Client` and `Northstar.Custom` does, but I'd assume client is to connect to the servers, and custom is for various gamemodes, and custom servers being hosting servers or something similar.
> 
> If someone knows whether there's any reason to read from one over the other lmk, I'd assume @GeckoEidechse would know more about this...

Yeah, so the core mods (`Northstar.Custom`, `Northstar.Client`, `Northstar.CustomServer`) should always be in sync in regards to version numbers. Similarly they should also be in sync with the version of `NorthstarLauncher.exe`. At least that's how we distribute them.

Now there are of course edge cases:

- A user could have tried to manually update Northstar but messed something up, e.g. they only replaced the mods folder (has happened before in a support ticket), or only replaced `NorthstarLauncher.exe`
- I think the exe only supports numeric version numbers, so for release candidates (e.g. `v1.7.1-rc1`) they might not match up fully (on the rc part).
- Developers will likely have a mismatch of version numbers between launcher and mods. Launcher when compiled from source for example is version `0.0.0.1` in the exe.

Hence I'd suggest checking version of core mods and launcher and throwing a warning about potentially corrupted install on mismatch.
If they do match, then that version would be considered as the currently installed version ^^

**Comment by 0neGal** [comment]
Okay so, the latest commit now checks all the various mod folders, and if they aren't all the same version it returns `unknown`, as before. If `Northstar Auto-Updates` is enabled in settings this would lead to NS re-installing, and of course if it's disabled nothing happens.

I don't know if this would suffice with your use case, with the testing builds and all? (@GeckoEidechse)

**Comment by GeckoEidechse** [comment]
> If `Northstar Auto-Updates` is enabled in settings this would lead to NS re-installing, and of course if it's disabled nothing happens.
> 
> I don't know if this would suffice with your use case, with the testing builds and all? (@GeckoEidechse)

Ye, as long as I can disable auto-updates if needed I'm happy :P


Regarding:
> Okay so, the latest commit now checks all the various mod folders, and if they aren't all the same version it returns `unknown`, as before.

I assume checking `NorthstarLauncher.exe` version is still planned? Just to avoid the case of end-user manually updating mods but failing to do the same for `NorthstarLauncher.exe`, then opening Viper which (wrongly) claims that Northstar is up-to-date. ^^

**Comment by 0neGal** [comment]
> I assume checking `NorthstarLauncher.exe` version is still planned? Just to avoid the case of end-user manually updating mods but failing to do the same for NorthstarLauncher.exe, then opening Viper which (wrongly) claims that Northstar is up-to-date. ^^

For that to happen, someone would have to manually download the archive either from GitHub or Thunderstore, then extract only the mods.

As we don't show the Northstar package in the mod browser, one would have to go out of their way to do this. Which seems unlikely to happen, and if it does happen the user likely knows this themselves.

Though feel free to lmk if you still think we should find a way to read the resource data...

**Comment by GeckoEidechse** [comment]
> For that to happen, someone would have to manually download the archive either from GitHub or Thunderstore, then extract only the mods.

It has actually happened before :I
(Though in that case they never used Viper but only ever manually updated.)

The scenario would be more like: user updates incorrectly by only updating mods folder -> asks for help in Northstar Discord server tickets -> gets told to use Viper instead for updating -> Viper claims user install up-to-date as it only checks mods folder.

**Comment by 0neGal** [comment]
In that case, I do see how it'd be useful, I'll try and figure something out later today.

If I can read the version it's very easy. (literally just adding the version to the `versions[]` variable in the `getNSVersion()` function)

I'll keep you posted! :)

**Comment by 0neGal** [comment]
Did quite a bit of searching testing multiple packages, and I can't seem to get any of them to give me the version number, either because they're wrappers for Windows only programs, or alike. So unless someone else can find a package that can actually get the version resource, as I can't really test the code on Windows, so even if it was Windows-only I couldn't reliably test it :p

But if someone finds that, I'm all in for adding it, otherwise I think it's best to just stick with the current method of checking the mods...

**Comment by GeckoEidechse** [comment]
> could be fixed by just checking if `NorthstarLauncher.exe` exists, albeit this wouldn't make sure the version is correct,

You could additionally also check creation/modified date of the exe. If it's older than release date of newest release (+/- some threshold), you could use that as an indicator that it's likely an older version, bypassing the need to check the actual version number of the `exe` (at the cost of some edge cases where somehow that date got changed by some other application).

**Comment by 0neGal** [comment]
> You could additionally also check creation/modified date of the exe. If it's older than release date of newest release (+/- some threshold)
That seems like a good idea at first, but now thinking about it, it seems like something that would be very unrealible. Wouldn't the `.exe` always have a creation date that's older than the release date?

And even if we were to give it, say, a 10 minute threshold, it still seems like something that would eventually just give back the wrong state/reply/version.

**Comment by 0neGal** [comment]
> The buffer date should probably be closer to 24h and just be used as an additional indicator that the version might be out of date. It's certainly not optimal but better than no check at all

That's what I was thinking as well. Essentially, if it far out of date, well... then it is out of date, and if it's too new than the version numbers should also be fine, it won't work 100% of the time, but it's still an improvement.
