### ISSUE TITLE
feat: Command line argument to skip Viper update check

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#99]
**What feature would you like added?**
Add a command line argument like `--skip-viper-update-check` to prevent Viper from performing an update check (and self-updating)

**Why should this feature be added?**
Mostly needed as part of #75 to prevent a Flatpak packaged version of the Viper AppImage perform an update in an environment that it wasn't designed for.

Might also be useful for other packaged solutions like [chocolatey](https://chocolatey.org/), [scoop](https://scoop.sh/), [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/), and [snap](https://snapcraft.io/).

**Additional Info**
I know that `viper.json` has a field called `"autoupdate"`. I'm not quite sure how it would come into play. Would `--skip-viper-update-check`cause Viper to ignore `"autoupdate"`. Or do we maybe wanna just somehow make sure that `"autoupdate"` is always set to `false` for packaged solutions?

**Comment by 0neGal** [comment]
It'll probably be named `--no-vp-updates` to align with `--update-vp`, it's quite simple to implement really. The question is, should this automatically remove the setting for auto updates inside the settings view, or should that be a separate option? (aka `--no-vp-update-btn` or similar), it already auto hides when using a format that doesn't support auto-updates. But I assume the Flatpak in #75 still has this option?



> I know that `viper.json` has a field called `"autoupdate"`. I'm not quite sure how it would come into play. Would `--skip-viper-update-check`cause Viper to ignore `"autoupdate"`. Or do we maybe wanna just somehow make sure that `"autoupdate"` is always set to `false` for packaged solutions?

It would overwrite it, so if it's already set to false, no difference, but if it's set to true it'll be as if it was false. I actually think if you install the AppImage it still puts that option in there, however it ignores it completely. Again the question is whether this option should also hide the auto-update settings option, or not.

**Comment by GeckoEidechse** [comment]
> The question is, should this automatically remove the setting for auto updates inside the settings view, or should that be a separate option? (aka --no-vp-update-btn or similar), it already auto hides when using a format that doesn't support auto-updates. But I assume the Flatpak in https://github.com/0neGal/viper/issues/75 still has this option?

I'd say it should also hide/remove the auto-update toggle switch. The Flatpak still shows the auto-update toggle as it just re-uses the AppImage binary.

Screenshot from Viper Flatpak settings screen:
![image](https://user-images.githubusercontent.com/40122905/159925044-c15673f2-fac3-49f7-9f33-f024082ba23e.png)

**Comment by 0neGal** [comment]
`--no-vp-updates` is now implemented :)!
